import fs from 'fs';
import path from 'path';
import type { Product } from '../features/catalog/domain/product';

// We will construct the 54 comprehensive Asian Mart products
export const fullCatalog: Product[] = [
  // --------------------------------------------------------------------------
  // CATEGORY 1: Daging & Unggas (Meat & Poultry)
  // --------------------------------------------------------------------------
  {
    id: 'ayam-kampung-segar',
    category: 'Daging & Unggas',
    price: 680,
    rating: 4.9,
    reviews: 142,
    stock: 25,
    image: 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?auto=format&fit=crop&w=1200&q=85',
    accent: '#c2785c',
    localizedContent: {
      id: { name: 'Ayam Kampung Segar', description: 'Ayam kampung utuh segar pilihan dengan daging padat, rendah lemak, dan cita rasa gurih alami. Bersih siap olah untuk opor, sup, atau ayam goreng.' },
      en: { name: 'Fresh Free-Range Chicken', description: 'Fresh whole free-range chicken with lean, tender meat and rich natural flavor. Cleaned and ready for roasting, curries, or traditional chicken soup.' },
      ja: { name: '新鮮な地鶏（丸鶏）', description: '引き締まった肉質と豊かなコクが特徴の新鮮な放し飼い地鶏（丸鶏）。ロースト、スープ、カレーなど本格煮込み料理に最適です。' },
      tl: { name: 'Sariwang Katutubong Manok', description: 'Sariwa at buong katutubong manok na may siksik na laman at likas na linamnam. Malinis at handang lutuin para sa tinola, adobo, o sabaw.' },
      vi: { name: 'Gà Ta Thả Vườn Tươi', description: 'Gà ta thả vườn nguyên con tươi ngon, thịt chắc ngọt, ít mỡ và đậm đà tự nhiên. Đã làm sạch, lý tưởng cho món gà luộc, nấu cháo hoặc cà ri.' },
      th: { name: 'ไก่บ้านสดทั้งตัว', description: 'ไก่บ้านสดทั้งตัวเนื้อแน่น ไขมันต่ำ ให้รสชาติหวานอร่อยตามธรรมชาติ ล้างสะอาดพร้อมปรุงสำหรับต้มยำ ไก่ทอด หรือแกงรสเด็ด' },
      hi: { name: 'ताज़ा देसी मुर्गा (साबुत)', description: 'ताज़ा साबुत देसी चिकन, पौष्टिक, कम वसा और प्राकृतिक स्वाद से भरपूर। करी, सूप या रोस्टिंग के लिए साफ और तैयार।' },
      zh: { name: '新鲜优质走地鸡（整只）', description: '精选新鲜散养走地鸡，肉质紧实细嫩，脂肪低且鲜香浓郁。已彻底清洗净膛，适宜煲汤、白斩或咖喱炖煮。' },
    },
  },
  {
    id: 'paha-ayam-fillet',
    category: 'Daging & Unggas',
    price: 450,
    rating: 4.8,
    reviews: 98,
    stock: 30,
    image: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?auto=format&fit=crop&w=1200&q=85',
    accent: '#d48b72',
    localizedContent: {
      id: { name: 'Paha Ayam Fillet Tanpa Tulang', description: 'Potongan daging paha ayam segar tanpa tulang dan kulit (500g). Daging juicy dan lembut, sempurna untuk sate, katsu, tumisan, atau barbeque.' },
      en: { name: 'Boneless Chicken Thigh Fillet', description: 'Fresh boneless, skinless chicken thigh fillets (500g). Juicy, flavorful, and versatile for yakitori, katsu, stir-fries, or grilling.' },
      ja: { name: '鶏もも肉（骨なしフィレ）', description: 'ジューシーで柔らかい骨なし・皮なし鶏もも肉フィレ（500g）。焼き鳥、チキンカツ、炒め物やグリルにぴったりです。' },
      tl: { name: 'Boneless Chicken Thigh Fillet', description: 'Sariwang fillet ng hita ng manok na walang buto (500g). Makatas at malambot, perpekto para sa inasal, stir-fry, o pritong katsu.' },
      vi: { name: 'Đùi Gà Rút Xương Tươi', description: 'Thịt đùi gà tươi rút xương, bỏ da (500g). Mềm ngọt và mọng nước, lý tưởng cho món xào, áp chảo, xiên que nướng hoặc gà rán.' },
      th: { name: 'สะโพกไก่เลาะกระดูก', description: 'เนื้อสะโพกไก่สดเลาะกระดูกและลอกหนัง (500 กรัม) เนื้อนุ่มฉ่ำ เหมาะสำหรับทำไก่ย่าง ผัด หรือทอดกรอบ' },
      hi: { name: 'हड्डी रहित चिकन थाई फ़िलेट', description: 'ताज़ा हड्डी रहित और बिना त्वचा वाला चिकन थाई फ़िलेट (500 ग्राम)। रसदार और कोमल, बारबेक्यू, कबाब या स्टिर-फ्राई के लिए उत्तम।' },
      zh: { name: '鲜嫩去骨鸡腿肉排', description: '精选新鲜去骨去皮鸡腿肉（500克）。鲜嫩多汁，口感紧致，非常适合制作照烧鸡排、日式炸鸡、串烧或快炒。' },
    },
  },
  {
    id: 'daging-sapi-rendang',
    category: 'Daging & Unggas',
    price: 1350,
    rating: 4.9,
    reviews: 184,
    stock: 20,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=85',
    accent: '#8b4513',
    localizedContent: {
      id: { name: 'Daging Sapi Potong Rendang 500g', description: 'Daging sapi bagian gandik/shank pilihan dipotong kotak khusus untuk masakan rendang, semur, atau gulai. Empuk meresap bumbu sempurna.' },
      en: { name: 'Beef Shank Cut for Rendang 500g', description: 'Premium beef shank cubes cut specifically for slow-cooked Indonesian rendang, stews, or rich curries. Tender and flavorful.' },
      ja: { name: 'レンダン用角切り牛すね肉 500g', description: 'インドネシア風煮込み料理レンダンやビーフシチューに最適な、煮込むほどに柔らかくなる厳選牛すね肉の角切り（500g）。' },
      tl: { name: 'Baka Cut para sa Rendang 500g', description: 'De-kalidad na hiwa ng baka para sa mabagal na pagluluto ng rendang, nilaga, o kaldereta. Lumalambot at kumakapit ang lasa ng pampalasa.' },
      vi: { name: 'Bắp Bò Cắt Khúc Nấu Rendang 500g', description: 'Thịt bắp bò tươi thái khúc vuông chuyên dùng cho món cà ri Rendang, bò kho hoặc hầm tiêu. Thịt thơm ngọt, ngấm vị.' },
      th: { name: 'เนื้อวัวหั่นเต๋าสำหรับเรนดัง 500g', description: 'เนื้อน่องลายวัวหั่นเต๋าคัดพิเศษ สำหรับเคี่ยวแกงเรนดังหรือสตูว์เนื้อ นุ่มละมุนลิ้นซึมซับเครื่องแกงเข้มข้น' },
      hi: { name: 'रेन्दांग के लिए बीफ़ शंक क्यूब्स 500g', description: 'धीमी आंच पर पकने वाले रेन्दांग और समृद्ध करी के लिए विशेष रूप से काटे गए बीफ़ शंक के टुकड़े।' },
      zh: { name: '经典仁当炖牛肉块 500克', description: '精选牛腱肉厚切方块，专为传统慢炖仁当咖喱或浓香炖牛肉设计，久煮不烂，肉香浓郁入味。' },
    },
  },
  {
    id: 'daging-slice-shabu',
    category: 'Daging & Unggas',
    price: 980,
    rating: 4.8,
    reviews: 120,
    stock: 35,
    image: 'https://images.unsplash.com/photo-1558030006-450675393462?auto=format&fit=crop&w=1200&q=85',
    accent: '#b22222',
    localizedContent: {
      id: { name: 'Daging Sapi Slice Shabu 300g', description: 'Irisan daging sapi tipis berlemak pas untuk hidangan shabu-shabu, sukiyaki, yakiniku, atau tumisan daging ala gyudon.' },
      en: { name: 'Thin Sliced Beef for Shabu 300g', description: 'Tender, thinly sliced premium beef with balanced marbling, ideal for shabu-shabu, sukiyaki, hotpot, or quick stir-fry gyudon.' },
      ja: { name: '牛しゃぶしゃぶ用スライス 300g', description: 'ほどよい霜降りと柔らかさが絶妙な薄切り牛肉（300g）。しゃぶしゃぶ、すき焼き、牛丼や炒め物に最適です。' },
      tl: { name: 'Manipis na Hiwang Baka para sa Shabu 300g', description: 'Manipis na hiwa ng malambot na baka, perpekto para sa hotpot, shabu-shabu, o mabilisang stir-fry.' },
      vi: { name: 'Thịt Bò Ba Chỉ Cắt Lát Shabu 300g', description: 'Thịt bò cắt lát mỏng mềm ngon với vân mỡ hài hòa, lý tưởng cho món lẩu nhúng shabu-shabu, sukiyaki hoặc cơm bò gyudon.' },
      th: { name: 'เนื้อสไลซ์บางสำหรับชาบู 300g', description: 'เนื้อวัวสไลซ์บางนุ่มละลายในปาก มีลายไขมันแทรกพอเหมาะ เหมาะสำหรับชาบู สุกี้ยากี้ หรือข้าวหน้าเนื้อ' },
      hi: { name: 'शाबू के लिए बारीक कटा बीफ़ 300g', description: 'हॉटपॉट, शाबू-शाबू और झटपट स्टिर-फ्राई के लिए उत्तम बारीक कटा हुआ कोमल बीफ़।' },
      zh: { name: '日式火锅原切肥牛薄片 300克', description: '优质原切薄片牛肉，油花分布均匀，肉质细腻多汁，涮火锅、寿喜烧或快炒日式牛肉饭皆宜。' },
    },
  },
  {
    id: 'sayap-ayam-segar',
    category: 'Daging & Unggas',
    price: 420,
    rating: 4.7,
    reviews: 86,
    stock: 28,
    image: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?auto=format&fit=crop&w=1200&q=85',
    accent: '#d97706',
    localizedContent: {
      id: { name: 'Sayap Ayam Segar 500g', description: 'Sayap ayam utuh segar (500g), kulit gurih renyah saat digoreng, sempurna untuk spicy wings, sup, atau panggang madu.' },
      en: { name: 'Fresh Chicken Wings 500g', description: 'Fresh whole chicken wings (500g). Crispy skin and tender meat, great for buffalo wings, grilling, or deep frying.' },
      ja: { name: '国産手羽先・手羽元 500g', description: 'ジューシーな旨味とパリッとした皮が自慢の新鮮な手羽先（500g）。唐揚げ、塩焼き、甘辛煮込みにどうぞ。' },
      tl: { name: 'Sariwang Pakpak ng Manok 500g', description: 'Sariwang pakpak ng manok (500g). Masarap iprito, i-barbeque, o lutuin sa sweet and sour sauce.' },
      vi: { name: 'Cánh Gà Tươi 500g', description: 'Cánh gà tươi nguyên cánh (500g), da giòn thịt ngọt, hoàn hảo cho món chiên nước mắm, nướng mật ong hoặc rim cay.' },
      th: { name: 'ปีกไก่สด 500g', description: 'ปีกไก่สดทั้งปีก (500 กรัม) หนังกรอบเนื้อนุ่ม เหมาะสำหรับทอดน้ำปลา ปิ้งย่าง หรืออบซอสบาร์บีคิว' },
      hi: { name: 'ताज़ा चिकन विंग्स 500g', description: 'ताज़ा साबुत चिकन विंग्स (500 ग्राम)। कुरकुरी त्वचा और रसीला मांस, ग्रिलिंग या फ्राइंग के लिए बेहतरीन।' },
      zh: { name: '新鲜中全鸡翅 500克', description: '精选新鲜全鸡翅（500克），肉质丰满多汁，皮脆肉嫩，极适宜制作可乐鸡翅、新奥尔良烤翅或蒜香炸鸡翅。' },
    },
  },
  {
    id: 'daging-kambing-muda',
    category: 'Daging & Unggas',
    price: 1550,
    rating: 4.8,
    reviews: 73,
    stock: 18,
    image: 'https://images.unsplash.com/photo-1603048588665-791ca8aea617?auto=format&fit=crop&w=1200&q=85',
    accent: '#78350f',
    localizedContent: {
      id: { name: 'Daging Kambing Muda Potong 500g', description: 'Potongan daging kambing muda empuk tanpa bau prengus berlebih. Sangat cocok untuk sate kambing, tongseng, gulai, atau sop kambing.' },
      en: { name: 'Tender Lamb / Mutton Cubes 500g', description: 'Tender, lean lamb cubes with mild game flavor. Perfect for satay skewers, rich mutton curries, or aromatic biryani.' },
      ja: { name: '子羊肉・マトン角切り 500g', description: 'クセが少なく柔らかい厳選ラム・マトン肉の角切り（500g）。アジア風串焼き（サテ）、スパイスカレー、ビリヤニに最適。' },
      tl: { name: 'Malambot na Karne ng Kambing 500g', description: 'Hiwa ng karneng kambing na malambot para sa kaldereta, kilawin, o inihaw na tuhog.' },
      vi: { name: 'Thịt Dê Non Cắt Khúc 500g', description: 'Thịt dê non tươi cắt khúc (500g) mềm ngọt, ít hôi, tuyệt hảo cho món lẩu dê, dê xào lăn hoặc nướng ngũ vị.' },
      th: { name: 'เนื้อแกะ/แพะหั่นเต๋า 500g', description: 'เนื้อแกะเนื้อแพะนุ่มหั่นเต๋า กลิ่นหอมเครื่องเทศกลมกล่อม เหมาะสำหรับแกงกะหรี่ สะเต๊ะ หรือข้าวหมกบริยานี' },
      hi: { name: 'कोमल मटन / लैम्ब क्यूब्स 500g', description: 'कोमल मटन क्यूब्स, मटन करी, कबाब और सुगंधित बिरयानी बनाने के लिए सर्वोत्तम।' },
      zh: { name: '鲜嫩羔羊肉块 500克', description: '精选优质羔羊肉切块（500克），肉质鲜嫩细密，膻味清淡，适合制作孜然烤羊肉串、羊肉手抓饭或清炖羊肉汤。' },
    },
  },
  {
    id: 'daging-cincang-sapi',
    category: 'Daging & Unggas',
    price: 650,
    rating: 4.7,
    reviews: 110,
    stock: 40,
    image: 'https://images.unsplash.com/photo-1588168333986-5078d3ae3976?auto=format&fit=crop&w=1200&q=85',
    accent: '#991b1b',
    localizedContent: {
      id: { name: 'Daging Sapi Cincang Premium 400g', description: 'Daging sapi giling segar dengan proporsi daging dan lemak seimbang (80/20). Bagus untuk bakso, martabak telur, saus bolognese, atau perkedel.' },
      en: { name: 'Ground Minced Beef 400g', description: 'Freshly ground lean beef with ideal 80/20 ratio. Versatile for Asian meatballs (bakso), stuffed pastries, patties, and stir-fries.' },
      ja: { name: '牛ひき肉 400g', description: '赤身と脂のバランスが良い新鮮な牛ひき肉（400g）。アジアン肉団子（バクソ）、ハンバーグ、炒め物や春巻きに。' },
      tl: { name: 'Giniling na Baka 400g', description: 'Sariwang giniling na baka na may tamang timpla ng taba, bagay sa embutido, lumpia, o giniling with potatoes.' },
      vi: { name: 'Thịt Bò Xay Tươi 400g', description: 'Thịt bò xay tươi nguyên chất (400g) tỷ lệ nạc mỡ chuẩn, thích hợp làm bò viên, chả giò, nhân bánh bao hoặc xào rau củ.' },
      th: { name: 'เนื้อวัวบดพรีเมียม 400g', description: 'เนื้อวัวบดสดคุณภาพสูง เหมาะสำหรับทำลูกชิ้นเนื้อ ผัดกะเพราเนื้อ หรือไส้ขนมต่างๆ' },
      hi: { name: 'ताज़ा कीमा बनाया हुआ बीफ़ 400g', description: 'ताज़ा कीमा, कबाब, मीटबॉल और विभिन्न स्वादिष्ट स्टिर-फ्राई के लिए उपयुक्त।' },
      zh: { name: '精选牛肉馅 400克', description: '新鲜精细绞制牛肉糜（400克），肥瘦黄金比例，适合制作手工牛肉丸、香浓牛肉酱、馅饼或肉饼。' },
    },
  },

  // --------------------------------------------------------------------------
  // CATEGORY 2: Makanan Laut (Seafood)
  // --------------------------------------------------------------------------
  {
    id: 'udang-windu-segar',
    category: 'Makanan Laut',
    price: 890,
    rating: 4.9,
    reviews: 165,
    stock: 25,
    image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&w=1200&q=85',
    accent: '#ea580c',
    localizedContent: {
      id: { name: 'Udang Windu Segar Pilihan 400g', description: 'Udang windu berukuran sedang-besar segar manis alami. Kulit renyah, daging kenyal padat, ideal untuk udang bakar madu, tempura, atau saus tiram.' },
      en: { name: 'Fresh Tiger Prawns 400g', description: 'Succulent black tiger prawns with firm, sweet meat. Cleaned and frozen fresh, ideal for garlic butter grilling, tempura, or spicy stir-fry.' },
      ja: { name: 'ブラックタイガー特大有頭海老 400g', description: 'プリプリとした歯ごたえと甘みが自慢のブラックタイガー有頭海老（400g）。塩焼き、天ぷら、ガーリックシュリンプに最高です。' },
      tl: { name: 'Sariwang Sugpo (Tiger Prawns) 400g', description: 'Malalaking sariwang sugpo na may matamis at siksik na laman. Masarap i-halabos, sinigang, o tempura.' },
      vi: { name: 'Tôm Sú Biển Tươi 400g', description: 'Tôm sú tươi tự nhiên con to, thịt săn chắc ngọt lịm. Thích hợp cho món hấp nước dừa, nướng muối ớt hoặc lăn bột chiên xù.' },
      th: { name: 'กุ้งกุลาดำสด 400g', description: 'กุ้งกุลาดำสดตัวโต เนื้อแน่นเด้งหวานฉ่ำ เหมาะสำหรับกุ้งเผา ต้มยำกุ้งน้ำข้น หรือทอดกระเทียม' },
      hi: { name: 'ताज़ा टाइगर झींगा (प्रॉन्स) 400g', description: 'रसीले बड़े टाइगर प्रॉन्स, स्वादिष्ट, ग्रिल करने, तंदूरी या रिच सीफ़ूड करी के लिए उपयुक्त।' },
      zh: { name: '新鲜特选黑虎虾 400克', description: '个头饱满的大黑虎虾（400克），虾肉紧致弹牙，鲜甜多汁。适宜盐烤、蒜蓉粉丝清蒸或制作经典冬阴功汤。' },
    },
  },
  {
    id: 'cumi-cumi-segar',
    category: 'Makanan Laut',
    price: 750,
    rating: 4.8,
    reviews: 94,
    stock: 22,
    image: 'https://images.unsplash.com/photo-1599084993091-1cb5c0721cc6?auto=format&fit=crop&w=1200&q=85',
    accent: '#64748b',
    localizedContent: {
      id: { name: 'Cumi-Cumi Segar Tube 400g', description: 'Cumi-cumi segar bersih siap olah. Tekstur kenyal lembut tanpa amis, sangat cocok untuk cumi saus padang, cumi bakar kecap, atau calamari crispy.' },
      en: { name: 'Fresh Squid Tubes 400g', description: 'Tender cleaned squid tubes (400g), free of skin and cartilage. Perfect for calamari rings, Asian chili stir-fries, or seafood noodles.' },
      ja: { name: '真イカ・アオリイカ切り身 400g', description: '下処理済みで調理しやすい新鮮イカ（400g）。柔らかく歯切れの良い食感で、フライ、炒め物、海鮮パスタに重宝します。' },
      tl: { name: 'Sariwang Pusit Tube 400g', description: 'Malinis na sariwang pusit para sa adobong pusit, inihaw na pusit, o pritong calamari rings.' },
      vi: { name: 'Mực Ống Tươi Làm Sạch 400g', description: 'Mực ống tươi nguyên con đã làm sạch (400g), thịt dày giòn ngọt, tuyệt vời cho món mực xào sa tế, hấp gừng hoặc chiên giòn.' },
      th: { name: 'ปลาหมึกสดล้างสะอาด 400g', description: 'ปลาหมึกกล้วยสดล้างสะอาดพร้อมปรุง เนื้อเด้งกรอบ เหมาะสำหรับผัดกะเพราหมึก ย่างซีอิ๊ว หรือทอดกรอบ' },
      hi: { name: 'ताज़ा स्क्विड (कैलमारी) 400g', description: 'ताज़ा साफ किया हुआ स्क्विड, क्रिस्पी रिंग्स या स्वादिष्ट मसालेदार स्टिर-फ्राई के लिए उत्तम।' },
      zh: { name: '净鲜鱿鱼卷筒 400克', description: '精选新鲜处理净膛鱿鱼（400克），肉质厚实脆嫩无腥味，适宜制作铁板鱿鱼、酱爆鱿鱼或炸黄金鱿鱼圈。' },
    },
  },
  {
    id: 'ikan-bandeng-presto',
    category: 'Makanan Laut',
    price: 680,
    rating: 4.8,
    reviews: 130,
    stock: 30,
    image: 'https://images.unsplash.com/photo-1534948216015-843149f72be3?auto=format&fit=crop&w=1200&q=85',
    accent: '#0284c7',
    localizedContent: {
      id: { name: 'Ikan Bandeng Duri Lunak Siap Goreng', description: 'Ikan bandeng presto khas Semarang dengan duri yang lunak menyeluruh. Gurih berbumbu rempah alami, tinggal digoreng dengan balutan telur.' },
      en: { name: 'Boneless Soft-Bone Milkfish', description: 'Traditional pressure-cooked milkfish with completely edible soft bones. Pre-seasoned with Asian herbs, ready to coat in egg and fry.' },
      ja: { name: '骨まで柔らかいサバヒー（ミルクフィッシュ）', description: '高圧加熱調理で小骨まで丸ごと食べられる伝統的な味付けサバヒー（ミルクフィッシュ）。卵をつけて揚げるだけで絶品です。' },
      tl: { name: 'Boneless Daing na Bangus', description: 'Tradisyunal na bangus na malambot ang tinik at may timpla na ng pampalasa, handang iprito sa kawali.' },
      vi: { name: 'Cá Măng Sữa Hầm Mềm Xương', description: 'Cá măng sữa chế biến theo công nghệ áp suất mềm rục toàn bộ xương, ướp gia vị đậm đà, chỉ cần chiên vàng là thưởng thức.' },
      th: { name: 'ปลานวลจันทร์ต้มกระดูกนิ่มพร้อมทอด', description: 'ปลานวลจันทร์ทะเลหมักเครื่องเทศตุ๋นจนก้างนิ่มเคี้ยวได้ทั้งตัว นำไปชุบไข่ทอดกรอบอร่อยมาก' },
      hi: { name: 'मुलायम हड्डियों वाली मिल्कशिश', description: 'विशेष रूप से पकाई गई स्वादिष्ट मिल्कशिश जिसकी हड्डियां भी खाई जा सकती हैं, तलने के लिए तैयार।' },
      zh: { name: '无骨酥香软骨虱目鱼', description: '经典南洋风味高压酥骨虱目鱼，整条鱼骨酥软可食，富含钙质与胶原蛋白，裹蛋液煎炸外酥里嫩。' },
    },
  },
  {
    id: 'ikan-salmon-fillet',
    category: 'Makanan Laut',
    price: 1280,
    rating: 4.9,
    reviews: 210,
    stock: 20,
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=1200&q=85',
    accent: '#f97316',
    localizedContent: {
      id: { name: 'Fillet Ikan Salmon Segar 300g', description: 'Potongan fillet salmon segar kaya Omega-3 dengan tekstur lembut mentega. Sempurna untuk pan-seared teriyaki, salmon mentai, atau sup miso.' },
      en: { name: 'Fresh Atlantic Salmon Fillet 300g', description: 'Fresh boneless Atlantic salmon fillet rich in Omega-3. Tender and buttery, ideal for pan-searing with teriyaki glaze, grilling, or baking.' },
      ja: { name: '生アトランティックサーモン切り身 300g', description: '脂の乗りが抜群な生サーモンの切り身（300g）。バター焼き、照り焼き、ホイル焼きやムニエルで極上の味わいをお楽しみください。' },
      tl: { name: 'Sariwang Salmon Fillet 300g', description: 'Sariwang fillet ng salmon na mayaman sa Omega-3. Masarap i-pan sear sa teriyaki sauce o gawing sinigang sa miso.' },
      vi: { name: 'Cá Hồi Tươi Cắt Lát Fillet 300g', description: 'Cá hồi tươi phi lê giàu dưỡng chất Omega-3 béo ngậy thơm ngon, hoàn hảo cho món áp chảo sốt bơ chanh hoặc nướng sốt teriyaki.' },
      th: { name: 'ปลาแซลมอนฟิลเลต์สด 300g', description: 'เนื้อปลาแซลมอนสดฟิลเลต์ไร้ก้าง ลายไขมันสวย อุดมด้วยโอเมก้า 3 เหมาะสำหรับสเต๊กปลาแซลมอนย่างซีอิ๊วหรือเทอริยากิ' },
      hi: { name: 'ताज़ा सैल्मन फ़िलेट 300g', description: 'ओमेगा-3 से भरपूर ताज़ा अटलांटिक सैल्मन फ़िलेट, पैन-सियरिंग, ग्रिलिंग या बेकिंग के लिए उत्तम।' },
      zh: { name: '深海三文鱼中段切片 300克', description: '优质大西洋三文鱼无骨整切，纹理清晰油润，富含深海Omega-3，适宜香煎照烧、黄油柠檬煎或制作三文鱼焗饭。' },
    },
  },
  {
    id: 'bakso-ikan-singapura',
    category: 'Makanan Laut',
    price: 380,
    rating: 4.7,
    reviews: 75,
    stock: 45,
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=1200&q=85',
    accent: '#38bdf8',
    localizedContent: {
      id: { name: 'Bakso Ikan Kenyal Premium 300g', description: 'Bakso ikan putih kenyal khas Asia Tenggara. Gurih alami dari ikan laut segar, cocok untuk mie kuah, steamboat, shabu-shabu, atau tumisan sayur.' },
      en: { name: 'Asian Fish Balls Premium 300g', description: 'Bouncy and springy Asian fish balls made from fresh sea fish. A must-have staple for noodle soups, steamboat hotpot, or stir-fries.' },
      ja: { name: '特製プリプリ魚団子（フィッシュボール） 300g', description: '弾力のあるプリプリ食感がたまらない東南アジア風白身魚のフィッシュボール（300g）。スープ麺や鍋料理の具材に欠かせません。' },
      tl: { name: 'Fish Balls Premium 300g', description: 'Masarap at makunat na fish balls para sa paboritong street food meryenda o pangsahog sa sopas.' },
      vi: { name: 'Cá Viên Chiên Thượng Hạng 300g', description: 'Cá viên trắng dai giòn tự nhiên chế biến từ cá biển tươi, món ăn kèm tuyệt hảo cho lẩu nước, hủ tiếu mì hoặc chiên ăn vặt.' },
      th: { name: 'ลูกชิ้นปลาเด้งพรีเมียม 300g', description: 'ลูกชิ้นปลาเนื้อแน่นเด้ง ทำจากเนื้อปลาทะเลแท้ ไม่คาว เหมาะสำหรับก๋วยเตี๋ยวน้ำใส ชาบู หรือสุกี้' },
      hi: { name: 'प्रीमियम एशियन फ़िश बॉल्स 300g', description: 'ताज़ी समुद्री मछली से बने स्वादिष्ट और उछालदार फ़िश बॉल्स, सूप नूडल्स और हॉटपॉट के लिए उत्तम।' },
      zh: { name: '传统手打高弹海鱼丸 300克', description: '选用新鲜深海白身鱼肉精心擂溃打制，口感紧实Q弹爽脆，鲜香无骨刺，为汤面、火锅打边炉必备美味。' },
    },
  },

  // --------------------------------------------------------------------------
  // CATEGORY 3: Sayuran Segar & Rimpang (Fresh Vegetables & Herbs)
  // --------------------------------------------------------------------------
  {
    id: 'baby-pakcoy-segar',
    category: 'Sayuran Segar',
    price: 120,
    rating: 4.9,
    reviews: 215,
    stock: 40,
    image: 'https://images.unsplash.com/photo-1594282486552-05b4d80fbb9f?auto=format&fit=crop&w=1200&q=85',
    accent: '#4a7c59',
    localizedContent: {
      id: { name: 'Baby Pakcoy Segar Hidroponik', description: 'Sawi sendok mini hijau segar renyah tanpa pestisida. Cepat matang, cocok untuk tumis bawang putih saus tiram atau pelengkap mie kuah.' },
      en: { name: 'Fresh Baby Bok Choy / Pakcoy', description: 'Crisp and tender hydroponic baby bok choy. Cooks in minutes, perfect for garlic oyster sauce stir-fry or noodle soup garnish.' },
      ja: { name: '新鮮ミニチンゲン菜（ベビー青梗菜）', description: 'シャキシャキとした食感と甘みが美味しい新鮮ベビー青梗菜。オイスターソースのにんにく炒めやラーメンのトッピングに最適。' },
      tl: { name: 'Sariwang Baby Bok Choy (Pechay)', description: 'Mura at sariwang baby bok choy. Madaling lutuin para sa ginisang pechay na may bawang at oyster sauce.' },
      vi: { name: 'Cải Thìa Baby Tươi Ngon', description: 'Cải thìa baby tươi non mơn mởn, vị giòn ngọt thanh khiết. Thích hợp xào dầu hào tỏi thơm hoặc nấu canh thịt bằm.' },
      th: { name: 'ผักกวางตุ้งไต้หวันสด (เบบี้กวางตุ้ง)', description: 'เบบี้ผักกวางตุ้งสดกรอบ หวานธรรมชาติ ผัดน้ำมันหอยไฟแดงอร่อยเลิศ หรือใส่ในบะหมี่น้ำ' },
      hi: { name: 'ताज़ा बेबी बोक चॉय (पाक चॉय)', description: 'कुरकुरा और ताज़ा बेबी बोक चॉय, लहसुन के साथ स्टिर-फ्राई या नूडल सूप में डालने के लिए बिल्कुल सही।' },
      zh: { name: '鲜嫩迷你有机小油菜（上海青）', description: '精选嫩甜爽脆鲜苗小油菜，叶绿茎嫩，快炒即熟，与蒜蓉蚝油热炒或置于高汤清汤面中皆清香怡人。' },
    },
  },
  {
    id: 'kangkung-hidroponik',
    category: 'Sayuran Segar',
    price: 150,
    rating: 4.9,
    reviews: 178,
    stock: 35,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=1200&q=85',
    accent: '#2d6a4f',
    localizedContent: {
      id: { name: 'Kangkung Segar Hidroponik 250g', description: 'Kangkung air segar hidroponik bebas lumpur dan pestisida. Batang renyah dan daun lembut, sempurna untuk tumis plecing kangkung atau terasi.' },
      en: { name: 'Fresh Water Spinach (Morning Glory) 250g', description: 'Fresh, clean hydroponic water spinach (morning glory). Crispy hollow stems and tender leaves, ideal for spicy sambal stir-fry.' },
      ja: { name: '新鮮空心菜（モーニンググローリー） 250g', description: '茎のシャキシャキ食感が癖になる新鮮な水耕栽培の空心菜（250g）。ニンニク唐辛子炒めやナンプラー炒めの大定番です。' },
      tl: { name: 'Sariwang Kangkong 250g', description: 'Malinis at sariwang kangkong. Perpekto para sa adobong kangkong, sinigang, o ginisang may bagoong.' },
      vi: { name: 'Rau Muống Nước Tươi Sạch 250g', description: 'Rau muống sạch cọng giòn non lá xanh mướt. Thích hợp cho món rau muống xào tỏi huyền thoại hoặc luộc chấm tương.' },
      th: { name: 'ผักบุ้งจีนสด 250g', description: 'ผักบุ้งจีนสดกรอบ ล้างสะอาดพร้อมผัด สำหรับเมนูยอดนิยมผักบุ้งไฟแดง รสเด็ดถึงใจ' },
      hi: { name: 'ताज़ा वाटर स्पिनैच (कलमी साग) 250g', description: 'ताज़ा और कुरकुरा वाटर स्पिनैच, लहसुन और लाल मिर्च के साथ गरमा-गरम तलने के लिए आदर्श।' },
      zh: { name: '新鲜嫩脆空心菜（通菜） 250克', description: '优质水培嫩心空心菜，梗爽脆、叶幼嫩，无泥沙杂质，适合制作经典的蒜蓉辣椒爆炒空心菜或虾酱炒通菜。' },
    },
  },
  {
    id: 'cabai-rawit-merah',
    category: 'Sayuran Segar',
    price: 220,
    rating: 4.8,
    reviews: 160,
    stock: 50,
    image: 'https://images.unsplash.com/photo-1588252303782-cb80119abd6d?auto=format&fit=crop&w=1200&q=85',
    accent: '#dc2626',
    localizedContent: {
      id: { name: 'Cabai Rawit Merah Super Pedas 150g', description: 'Cabai rawit merah petik segar dengan tingkat kepedasan maksimal. Menghasilkan sambal ulek bercita rasa pedas mantap menggugah selera.' },
      en: { name: 'Fresh Red Bird\'s Eye Chili 150g', description: 'Fiery fresh red bird\'s eye chilies (150g). Packs an intense, sharp heat essential for Southeast Asian sambals, curries, and dipping sauces.' },
      ja: { name: '激辛生赤唐辛子（プリッキーヌ） 150g', description: '鮮烈な辛味と爽やかな香りが特徴の生赤唐辛子（150g）。東南アジアのサンバル、激辛タイ料理、トムヤムクンに不可欠。' },
      tl: { name: 'Sariwang Siling Labuyo 150g', description: 'Napakanghang na pulang siling labuyo (150g). Pampaanghang sa sawsawan, bicol express, at sisig.' },
      vi: { name: 'Ớt Hiểm Đỏ Siêu Cay 150g', description: 'Ớt hiểm đỏ tươi nhỏ cay nồng bùng cháy (150g), gia vị cốt lõi cho các loại nước chấm, muối ớt và món cay Đông Nam Á.' },
      th: { name: 'พริกขี้หนูสวนสีแดงสด 150g', description: 'พริกขี้หนูสวนสีแดงสดแท้ เผ็ดจี๊ดถึงใจ กลิ่นหอม สำหรับทำน้ำจิ้มซีฟู้ด ส้มตำ หรือต้มยำ' },
      hi: { name: 'ताज़ा तीखी लाल बर्ड्स आई मिर्च 150g', description: 'तीखी और ताज़ा छोटी लाल मिर्च, पारंपरिक एशियाई व्यंजनों और तीखी चटनी के लिए बेहद ज़रूरी।' },
      zh: { name: '新鲜劲辣朝天指天椒（鸟眼椒） 150克', description: '新鲜采摘特级红指天椒（150克），辣度饱满纯正，香味浓烈，适合用于泰式舂酸辣汁、秘制辣椒酱或麻辣蘸料。' },
    },
  },
  {
    id: 'trio-rimpang-segar',
    category: 'Sayuran Segar',
    price: 320,
    rating: 4.9,
    reviews: 145,
    stock: 40,
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=1200&q=85',
    accent: '#b45309',
    localizedContent: {
      id: { name: 'Trio Rimpang Dapur (Jahe, Kunyit, Lengkuas)', description: 'Paket 3 rimpang dapur segar (jahe emprit, kunyit tua, dan lengkuas muda). Fondasi aroma bumbu dasar kuning dan merah khas Nusantara.' },
      en: { name: 'Fresh Aromatics Trio (Ginger, Turmeric, Galangal)', description: 'Fresh culinary rhizome bundle featuring root ginger, golden turmeric, and tender galangal. The essential spice foundation for Asian cooking.' },
      ja: { name: 'アジアン生根生姜トリオ（生姜・生ウコン・ガランガル）', description: 'アジア料理の味の土台となる生薬味3種セット（生姜、生ターメリック、ガランガル）。カレーやスープ、肉魚の下味に重宝します。' },
      tl: { name: 'Sariwang Luya, Luyang Dilaw at Galangal Bundle', description: 'Kumbinasyon ng sariwang luya, luyang dilaw (turmeric), at galangal para sa masasarap na sabaw at ulam.' },
      vi: { name: 'Bộ Ba Củ Gia Vị Tươi (Gừng, Nghệ, Riềng)', description: 'Bộ ba củ gia vị tươi thiết yếu gồm gừng già, nghệ vàng và riềng non. Khử mùi tanh và tạo mùi vị đặc trưng cho món kho, canh, cà ri.' },
      th: { name: 'ชุดสามเกลอรากสมุนไพรสด (ขิง ขมิ้น ข่า)', description: 'รวมรากสมุนไพรสด 3 ชนิด ขิงแก่ ขมิ้นชัน และข่าอ่อน กลิ่นหอมดับคาวเนื้อสัตว์ เพิ่มรสชาติอาหารให้กลมกล่อม' },
      hi: { name: 'ताज़ा अदरक, हल्दी और गलगल का कॉम्बो', description: 'ताज़ी अदरक, कच्ची हल्दी और गलगल का आवश्यक मसाला पैक, करी और एशियाई सूप का आधार।' },
      zh: { name: '南洋鲜香三生姜组合（老姜、鲜黄姜、高良姜）', description: '亚洲厨房核心鲜辛三宝组合：优选鲜老姜、高山黄姜与南洋生良姜。去腥提鲜，赋予咖喱与浓汤独特的层次香气。' },
    },
  },
  {
    id: 'sereh-dan-daun-jeruk',
    category: 'Sayuran Segar',
    price: 180,
    rating: 4.8,
    reviews: 95,
    stock: 35,
    image: 'https://images.unsplash.com/photo-1509358271058-acd22cc93898?auto=format&fit=crop&w=1200&q=85',
    accent: '#65a30d',
    localizedContent: {
      id: { name: 'Paket Sereh Wangi & Daun Jeruk Purut', description: 'Kombinasi batang sereh wangi segar dan daun jeruk purut hijau pekat. Memberikan sensasi kesegaran citrus alami pada masakan soto, gulai, dan rendang.' },
      en: { name: 'Fresh Lemongrass & Kaffir Lime Leaves Bundle', description: 'Fragrant lemongrass stalks paired with dark green kaffir lime leaves. Essential citrus bouquet for Tom Yum, Indonesian soto, and coconut curries.' },
      ja: { name: '生レモングラス＆バイマックルー（こぶみかんの葉）セット', description: '爽やかな柑橘香のフレッシュレモングラスとバイマックルー（こぶみかんの葉）のセット。トムヤムクンやココナッツスープに必須のハーブ。' },
      tl: { name: 'Tanglad (Lemongrass) at Kaffir Lime Leaves', description: 'Mabangong tanglad at dahon ng kaffir lime para sa mabangong sabaw at inihaw na manok.' },
      vi: { name: 'Sả Cây Tươi & Lá Chanh Kaffir', description: 'Sả cây tươi giòn đượm tinh dầu cùng lá chanh kaffir xanh ngát. Tạo hương thơm thảo mộc tuyệt hảo cho món lẩu Thái, gà hấp hoặc canh chua.' },
      th: { name: 'ชุดตะไคร้สดและใบมะกรูด', description: 'ตะไคร้สดกลิ่นหอมและใบมะกรูดสีเขียวเข้ม เครื่องต้มยำแกงป่า ช่วยชูรสให้อาหารน่ารับประทาน' },
      hi: { name: 'ताज़ा लेमनग्रास और काफिर लाइम की पत्तियां', description: 'सुगंधित लेमनग्रास और काफिर लाइम की ताज़ा पत्तियां, थाई और एशियाई करी में ताज़गी भरने के लिए।' },
      zh: { name: '新鲜香茅柠檬草与马蜂柑柠檬叶套组', description: '天然芳香草本精选：新鲜香茅草段搭配深绿青柠叶，轻揉即散发扑鼻柠檬清香，为冬阴功与南洋椰汁鸡汤之灵魂。' },
    },
  },
  {
    id: 'bawang-merah-brebes',
    category: 'Sayuran Segar',
    price: 260,
    rating: 4.9,
    reviews: 135,
    stock: 50,
    image: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&w=1200&q=85',
    accent: '#9f1239',
    localizedContent: {
      id: { name: 'Bawang Merah Brebes Pilihan 250g', description: 'Bawang merah Brebes kering berkualitas tinggi dengan kadar air rendah dan rasa manis gurih khas. Cocok untuk bumbu halus dan bawang goreng renyah.' },
      en: { name: 'Asian Shallots 250g', description: 'Fragrant and sweet red Asian shallots. Low water content makes them perfect for crispy fried shallot garnishes and rich aromatic curry pastes.' },
      ja: { name: 'アジアン赤エシャロット（ホムデン） 250g', description: '強い香りと深いコクを持つ東南アジア産赤エシャロット（250g）。香ばしいフライドシャロット作りや、炒め物の薬味に不可欠。' },
      tl: { name: 'Sibuyas Tagalog (Shallots) 250g', description: 'Maliliit at mababangong sibuyas Tagalog. Masarap gawing panggisa o crispy fried shallots.' },
      vi: { name: 'Hành Tím Khô Nguyên Củ 250g', description: 'Hành tím củ chắc vỏ bóng thơm nồng đặc trưng, dùng phi vàng giòn rắc lên món ăn hoặc băm nhỏ tao thơm bùng vị.' },
      th: { name: 'หอมแดงไทยคัดพิเศษ 250g', description: 'หอมแดงแห้งหัวแน่น กลิ่นหอมรสเข้มข้น ทำหอมเจียวกรอบอร่อย หรือตำน้ำพริกเครื่องแกง' },
      hi: { name: 'एशियाई छोटे लाल प्याज़ (शैलोट्स) 250g', description: 'सुगंधित छोटे एशियाई प्याज, कुरकुरा तलने और करी पेस्ट का स्वाद बढ़ाने के लिए उपयुक्त।' },
      zh: { name: '精选高香紫皮小干葱头 250克', description: '皮红肉紫、水分含量低、葱香极为醇厚的优质小红葱（250克）。炸制葱油酥脆可口，炒菜爆锅香飘满屋。' },
    },
  },
  {
    id: 'jamur-enoki-segar',
    category: 'Sayuran Segar',
    price: 110,
    rating: 4.8,
    reviews: 90,
    stock: 45,
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=85',
    accent: '#e2e8f0',
    localizedContent: {
      id: { name: 'Jamur Enoki Segar 100g', description: 'Jamur enoki putih bersih segar dengan tekstur renyah lembut. Lezat untuk isian shabu-shabu, sukiyaki, sup miso, atau digoreng krispi.' },
      en: { name: 'Fresh Enoki Mushrooms 100g', description: 'Crisp, slender golden needle mushrooms (enoki). A staple addition for hotpot, Japanese soups, ramen bowls, or crispy fried tempura.' },
      ja: { name: '新鮮えのき茸 100g', description: 'シャキシャキの歯ざわりが楽しい国産えのき茸（100g）。お鍋、味噌汁、すき焼き、ベーコン巻き炒めにぴったり。' },
      tl: { name: 'Sariwang Enoki Mushrooms 100g', description: 'Maninipis at malutong na enoki mushrooms, paborito sa hotpot, ramen, o pritong crispy tempura.' },
      vi: { name: 'Nấm Kim Châm Tươi 100g', description: 'Nấm kim châm trắng giòn ngọt tự nhiên, món nhúng lẩu không thể thiếu, tuyệt ngon khi cuộn ba chỉ bò nướng hoặc nấu canh rong biển.' },
      th: { name: 'เห็ดเข็มทองสด 100g', description: 'เห็ดเข็มทองสดขาวสะอาด เส้นกรุบกรอบ สำหรับใส่ในหม้อไฟชาบู สุกี้ ต้มยำ หรือพันเบคอนย่าง' },
      hi: { name: 'ताज़ा एनोकी मशरूम 100g', description: 'कुरकुरे और पतले एनोकी मशरूम, जापानी सूप, हॉटपॉट और नूडल्स के लिए बेहतरीन।' },
      zh: { name: '鲜嫩金针菇（金菇） 100克', description: '洁白整齐、口感脆嫩爽滑的新鲜金针菇（100克）。涮火锅、煮麻辣烫、蒜蓉清蒸或培根肉卷烤制皆为上选。' },
    },
  },
  {
    id: 'jamur-shiitake-segar',
    category: 'Sayuran Segar',
    price: 280,
    rating: 4.9,
    reviews: 112,
    stock: 30,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=1200&q=85',
    accent: '#44403c',
    localizedContent: {
      id: { name: 'Jamur Shiitake Segar 150g', description: 'Jamur shiitake segar berdaging tebal dengan aroma umami tanah yang khas. Nikmat ditumis dengan sayur, dimasukkan ke dalam sup, atau dipanggang.' },
      en: { name: 'Fresh Shiitake Mushrooms 150g', description: 'Plump, earthy fresh shiitake mushrooms brimming with natural umami. Perfect for braising, Asian noodle broths, or grilling with soy butter.' },
      ja: { name: '肉厚生椎茸（生しいたけ） 150g', description: '豊かな香りと肉厚な歯ごたえが自慢の新鮮生しいたけ（150g）。網焼きバター醤油、すき焼き、天ぷらや煮物に。' },
      tl: { name: 'Sariwang Shiitake Mushrooms 150g', description: 'Makapal at malinamnam na shiitake mushrooms para sa pancit, chop suey, at mga malasang sabaw.' },
      vi: { name: 'Nấm Hương Tươi (Shiitake) 150g', description: 'Nấm hương tươi thịt dày mọng nước hương thơm thảo mộc tự nhiên. Thích hợp xào thập cẩm, hầm gà hoặc nấu súp hải sản.' },
      th: { name: 'เห็ดหอมสด 150g', description: 'เห็ดหอมสดเนื้อหนานุ่ม รสชาติเข้มข้นอูมามิ เหมาะสำหรับผัดผักรวมมิตร ตุ๋นยาจีน หรือย่างเนยกระเทียม' },
      hi: { name: 'ताज़ा शियाटेक मशरूम 150g', description: 'प्राकृतिक उमामी स्वाद से भरपूर ताज़ा शियाटेक मशरूम, एशियाई सूप और स्टिर-फ्राई के लिए उत्तम।' },
      zh: { name: '肉厚浓香鲜香菇 150克', description: '厚伞深色、菇香馥郁的新鲜优质生香菇（150克）。富含有益多糖与天然谷氨酸鲜味，炖鸡汤、素炒蔬菜或炭火慢烤均回味无穷。' },
    },
  },

  // --------------------------------------------------------------------------
  // CATEGORY 4: Bumbu Dapur (Spices, Pastes & Seasonings)
  // --------------------------------------------------------------------------
  {
    id: 'bumbu-rendang-otentik',
    category: 'Bumbu Dapur',
    price: 350,
    rating: 4.9,
    reviews: 230,
    stock: 50,
    image: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=1200&q=85',
    accent: '#854d0e',
    localizedContent: {
      id: { name: 'Bumbu Rendang Padang Otentik 150g', description: 'Pasta bumbu basah rendang tradisional Minang dengan rempah lengkap dan kelapa sangrai (kerisik). Masak rendang daging lezat tanpa repot.' },
      en: { name: 'Authentic Padang Rendang Paste 150g', description: 'Slow-simmered Indonesian rendang curry paste with toasted coconut, galangal, and aromatic spices. Produces rich, caramelized beef rendang.' },
      ja: { name: '本格パダン風レンダンペースト 150g', description: '本場ミナンカバウの秘伝スパイスとローストココナッツを贅沢に使用した本格レンダンペースト。牛肉と煮込むだけで世界一の美味しさを再現。' },
      tl: { name: 'Authentic Beef Rendang Paste 150g', description: 'Tradisyunal na timpla ng rendang paste na may gata at mababangong pampalasa, napakadaling lutuin para sa masarap na baka.' },
      vi: { name: 'Sốt Cà Ri Bò Rendang Padang 150g', description: 'Gói gia vị sốt Rendang truyền thống đảo Sumatra với dừa rang và thảo mộc, giúp nấu món bò Rendang chuẩn vị thơm ngon dễ dàng.' },
      th: { name: 'พริกแกงเรนดังอินโดนีเซียแท้ 150g', description: 'พริกแกงเรนดังสูตรต้นตำรับจากปาดัง ผสมเนื้อมะพร้าวคั่วและเครื่องเทศหอมกรุ่น ปรุงเนื้อวัวเรนดังรสเข้มข้น' },
      hi: { name: 'प्रामाणिक रेन्दांग करी पेस्ट 150g', description: 'भुने हुए नारियल और सुगंधित मसालों से बना इंडोनेशियाई रेन्दांग करी पेस्ट, लाजवाब स्वाद के लिए।' },
      zh: { name: '南洋正宗巴东仁当咖喱炖肉酱 150克', description: '遵循苏门答腊传统手作配方，富含炒香椰丝与二十余种纯天然香料。仅需慢炖牛肉，即可还原享誉全球的浓醇仁当风味。' },
    },
  },
  {
    id: 'bumbu-soto-ayam-kuning',
    category: 'Bumbu Dapur',
    price: 250,
    rating: 4.8,
    reviews: 140,
    stock: 45,
    image: 'https://images.unsplash.com/photo-1547496502-affa22d38842?auto=format&fit=crop&w=1200&q=85',
    accent: '#eab308',
    localizedContent: {
      id: { name: 'Bumbu Soto Ayam Kuning Gurih 100g', description: 'Racikan bumbu soto ayam kuning khas Nusantara dengan kunyit pilihan, serai, dan rempah harum. Kuah soto kuning hangat, gurih, dan menyegarkan.' },
      en: { name: 'Yellow Chicken Soto Soup Paste 100g', description: 'Indonesian aromatic yellow chicken broth paste infused with turmeric, lemongrass, and shallots. Creates comforting, savory chicken soto soup.' },
      ja: { name: 'ソトアヤムの素（ウコン風味チキンスープ） 100g', description: '生ウコン、レモングラス、生姜が香るインドネシア定番の黄色いチキンスープ「ソトアヤム」の素。体が温まる優しい味わいです。' },
      tl: { name: 'Soto Ayam Yellow Chicken Soup Paste 100g', description: 'Pampalasa para sa masarap at mainit na Indonesian yellow chicken soup na may luyang dilaw at tanglad.' },
      vi: { name: 'Gia Vị Nấu Súp Gà Vàng Soto Ayam 100g', description: 'Gói gia vị súp gà nghệ truyền thống Indonesia với sả thơm và hành phi. Mang đến nồi súp thanh ngọt ấm bụng.' },
      th: { name: 'เครื่องปรุงต้มซุปไก่ขมิ้นโซโตอายัม 100g', description: 'เครื่องเทศสำหรับทำซุปไก่ขมิ้นสไตล์อินโดนีเซีย กลิ่นหอมตะไคร้ ซดคล่องคอสดชื่น' },
      hi: { name: 'येलो चिकन सोतो सूप पेस्ट 100g', description: 'हल्दी और लेमनग्रास से भरपूर स्वादिष्ट चिकन सूप पेस्ट, पौष्टिक और ताजगी से भरा।' },
      zh: { name: '印尼传统黄姜鸡汤料酱（索托鸡汤） 100克', description: '精选黄金郁金、香茅与鲜葱蒜精心熬制，汤色金黄清亮，入口香气温润解腻，为印尼最具国民代表性的暖胃鸡汤料包。' },
    },
  },
  {
    id: 'bumbu-nasi-goreng-spesial',
    category: 'Bumbu Dapur',
    price: 220,
    rating: 4.9,
    reviews: 310,
    stock: 60,
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=1200&q=85',
    accent: '#b91c1c',
    localizedContent: {
      id: { name: 'Bumbu Nasi Goreng Spesial Rempah 100g', description: 'Bumbu pasta nasi goreng dengan terasi bakar, bawang merah, cabai, dan kecap manis. Praktis membuat nasi goreng harum beraroma smoky khas kaki lima.' },
      en: { name: 'Special Fried Rice (Nasi Goreng) Paste 100g', description: 'Ready-to-use Indonesian fried rice paste crafted with shallots, chilies, sweet soy, and roasted shrimp paste. Recreates street-food style nasi goreng.' },
      ja: { name: '本格ナシゴレンの素（スパイスペースト） 100g', description: '赤エシャロット、唐辛子、ケチャップマニスと香ばしいシュリンプペーストをブレンドした特製ナシゴレンの素。屋台の香ばしさを手軽に食卓へ。' },
      tl: { name: 'Nasi Goreng Special Paste 100g', description: 'Gia vị para sa masarap na Indonesian fried rice na may lasang sibuyas, sili, at matamis na toyo.' },
      vi: { name: 'Sốt Cơm Chiên Nasi Goreng Đặc Biệt 100g', description: 'Sốt gia vị cơm chiên Indonesia thơm lừng mắm tôm nướng và nước tương ngọt, chỉ cần đảo cùng cơm nóng là có đĩa cơm chiên chuẩn vị.' },
      th: { name: 'ซอสผัดข้าวผัดนาซีโกเร็งสูตรพิเศษ 100g', description: 'ซอสสำหรับผัดข้าวผัดอินโดนีเซียแท้ หอมกลิ่นกระทะและเครื่องเทศ ผัดกับข้าวสวยร้อนๆ อร่อยทันใจ' },
      hi: { name: 'स्पेशल नासी गोरेंग फ्राइड राइस पेस्ट 100g', description: 'एशियाई स्ट्रीट-स्टाइल फ्राइड राइस बनाने के लिए तैयार स्वादिष्ट पेस्ट।' },
      zh: { name: '经典印尼特级炒饭酱（纳西炒饭） 100克', description: '融合烘烤虾酱、紫葱头与浓稠甜酱油之精华，翻炒冷饭镬气十足，轻松复刻南洋街头排档经典招牌炒饭。' },
    },
  },
  {
    id: 'pasta-tom-yum-thailand',
    category: 'Bumbu Dapur',
    price: 340,
    rating: 4.8,
    reviews: 190,
    stock: 40,
    image: 'https://images.unsplash.com/photo-1548946526-f69e2424cf45?auto=format&fit=crop&w=1200&q=85',
    accent: '#ef4444',
    localizedContent: {
      id: { name: 'Pasta Tom Yum Thailand Asli 227g', description: 'Pasta bumbu Tom Yum khas Thailand dengan rasa asam pedas menyegarkan dan aroma rempah kaffir lime serta serai yang otentik.' },
      en: { name: 'Authentic Thai Tom Yum Paste 227g', description: 'Traditional spicy and sour Thai Tom Yum soup paste infused with lemongrass, galangal, kaffir lime, and chili. Just add shrimp and mushrooms.' },
      ja: { name: '本場タイ産 トムヤムペースト 227g', description: 'レモングラス、こぶみかんの葉、ガランガルの清々しい香りと酸味・辛味が際立つ本格トムヤムスープペースト。海老やキノコを加えるだけ。' },
      tl: { name: 'Thai Tom Yum Soup Paste 227g', description: 'Maasim at maanghang na Tom Yum paste mula sa Thailand, perpekto para sa masarap na seafood soup.' },
      vi: { name: 'Sốt Nấu Canh Chua Cay Tom Yum Thái 227g', description: 'Cốt gia vị lẩu và canh Tom Yum chuẩn Thái Lan vị chua cay thanh mát kích thích vị giác, nấu cùng tôm mực cực kỳ hấp dẫn.' },
      th: { name: 'น้ำพริกต้มยำกุ้งสูตรไทยแท้ 227g', description: 'พริกแกงต้มยำสำเร็จรูป หอมกลิ่นข่า ตะไคร้ ใบมะกรูด เปรี้ยวเผ็ดครบรสตามตำรับอาหารไทยแท้' },
      hi: { name: 'प्रामाणिक थाई टॉम यम पेस्ट 227g', description: 'पारंपरिक खट्टा और तीखा थाई सूप पेस्ट, सीफ़ूड और मशरूम सूप के लिए एकदम सही।' },
      zh: { name: '泰国原装特级冬阴功酸辣汤料酱 227克', description: '泰国地道古法冬阴功浓缩酱，精炼青柠酸汁、香茅草与南姜精油，酸辣开胃，加入海虾与菌菇即可煮出五星级泰式酸辣汤。' },
    },
  },
  {
    id: 'pasta-kari-hijau-thai',
    category: 'Bumbu Dapur',
    price: 320,
    rating: 4.7,
    reviews: 105,
    stock: 35,
    image: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=1200&q=85',
    accent: '#15803d',
    localizedContent: {
      id: { name: 'Pasta Kari Hijau Thailand 200g', description: 'Bumbu kari hijau pedas lembut khas Thailand dengan cabai hijau segar, daun ketumbar, dan rempah aromatik. Cocok dipadu dengan santan dan ayam.' },
      en: { name: 'Thai Green Curry Paste 200g', description: 'Aromatic Thai green curry paste made from fresh green chilies, coriander root, and lemongrass. Combines wonderfully with coconut milk and chicken.' },
      ja: { name: 'タイ風グリーンカレーペースト 200g', description: '青唐辛子の爽やかな辛味とハーブの香りが調和したグリーンカレーペースト。ココナッツミルクと鶏肉・ナスを加えて本場の味に。' },
      tl: { name: 'Thai Green Curry Paste 200g', description: 'Mabangong green curry paste para sa masarap na ulam na may gata at manok.' },
      vi: { name: 'Gia Vị Cà Ri Xanh Thái Lan 200g', description: 'Cốt cà ri xanh với vị cay êm dịu từ ớt xanh tươi và thảo mộc, nấu cùng nước cốt dừa và thịt gà đậm đà thanh vị.' },
      th: { name: 'พริกแกงเขียวหวานไทยแท้ 200g', description: 'พริกแกงเขียวหวานกลิ่นหอมใบโหระพาและพริกขี้หนูเขียว ปรุงแกงเขียวหวานไก่ใส่มะเขือเปราะรสกลมกล่อม' },
      hi: { name: 'थाई ग्रीन करी पेस्ट 200g', description: 'ताज़ी हरी मिर्च और सुगंधित मसालों से बना थाई ग्रीन करी पेस्ट, नारियल के दूध के साथ पकाएं।' },
      zh: { name: '泰国青咖喱特级调味酱 200克', description: '选用鲜摘鲜绿朝天椒与芫荽根精磨研制，草本清香四溢，辣中回甘，搭配浓郁椰浆与鸡肉焖煮风味绝伦。' },
    },
  },
  {
    id: 'garam-masala-india',
    category: 'Bumbu Dapur',
    price: 380,
    rating: 4.9,
    reviews: 125,
    stock: 45,
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=1200&q=85',
    accent: '#b45309',
    localizedContent: {
      id: { name: 'Garam Masala Rempah India Murni 100g', description: 'Campuran bubuk rempah harum India berkualitas tinggi (kapulaga, kayu manis, cengkeh, ketumbar). Memberikan kedalaman rasa pada kari dan biryani.' },
      en: { name: 'Authentic Indian Garam Masala Powder 100g', description: 'Fragrant warm spice blend of roasted cardamom, cinnamon, cloves, cumin, and coriander. Adds warm depth to Indian curries, lentils, and biryani.' },
      ja: { name: '本格インド産 ガラムマサラ特製パウダー 100g', description: 'カルダモン、シナモン、クローブ、クミンなど香り高い焙煎スパイスを贅沢にブレンド。カレーの仕上げや肉料理に深いコクと香りをプラス。' },
      tl: { name: 'Pure Indian Garam Masala 100g', description: 'Mabangong timpla ng pampalasa mula sa India para sa masasarap na curry, karne, at gulay.' },
      vi: { name: 'Bột Gia Vị Garam Masala Ấn Độ 100g', description: 'Hỗn hợp gia vị thảo mộc thơm nồng đặc trưng Ấn Độ (bạch đậu khấu, quế, đinh hương, thì là), điểm nhấn hoàn hảo cho món cà ri.' },
      th: { name: 'ผงการัมมาซาลาเครื่องเทศอินเดียแท้ 100g', description: 'เครื่องเทศผสมกลิ่นหอมอบอุ่นสไตล์อินเดีย ผสมกระวาน อบเชย และกานพลู เพิ่มความหอมล้ำลึกให้แกงกะหรี่และข้าวหมก' },
      hi: { name: 'शुद्ध भारतीय गरम मसाला पाउडर 100g', description: 'इलायची, दालचीनी, लौंग और जीरे से बना सुगंधित गरम मसाला, करी और दाल में भरपूर स्वाद जोड़ने के लिए।' },
      zh: { name: '印度正统浓香复合葛拉姆马萨拉香料粉 100克', description: '传承北印度宫廷烘焙研磨工艺，荟萃绿豆蔻、肉桂、丁香与小茴香，出锅前撒入为各类浓香咖喱与手抓饭注入迷人灵魂香气。' },
    },
  },
  {
    id: 'terasi-udang-bakar',
    category: 'Bumbu Dapur',
    price: 180,
    rating: 4.8,
    reviews: 175,
    stock: 55,
    image: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=1200&q=85',
    accent: '#451a03',
    localizedContent: {
      id: { name: 'Terasi Udang Rebon Matang Bakar 100g', description: 'Terasi udang rebon fermentasi alami yang telah dipanggang matang. Beraroma gurih tajam menggoda, siap pakai untuk sambal terasi dan aneka tumisan.' },
      en: { name: 'Roasted Fermented Shrimp Paste (Terasi/Belacan) 100g', description: 'Naturally fermented tiny shrimp paste (terasi/belacan) pre-roasted for convenience. Delivers the signature umami punch to Southeast Asian sambals.' },
      ja: { name: 'ローストシュリンプペースト（トラシ／ブラチャン） 100g', description: '小エビを発酵させ香ばしくローストした発酵シュリンプペースト。サンバルや炒め物に少量加えるだけで劇的な旨味とコクを生み出します。' },
      tl: { name: 'Lutong Bagoong Alamang (Belacan) 100g', description: 'Ginisang bagoong alamang na may malakas at malasang umami, perpekto sa mangga, kare-kare, o sawsawan.' },
      vi: { name: 'Mắm Ruốc Tôm Nướng Thơm (Belacan) 100g', description: 'Mắm ruốc tôm lên men tự nhiên nướng chín dậy mùi thơm béo mặn mà, bí quyết làm nên các món kho quẹt và chấm cay trứ danh.' },
      th: { name: 'กะปิกุ้งเคยคั่วหอม 100g', description: 'กะปิแท้ทำจากกุ้งเคยธรรมชาติ คั่วจนหอม ปรุงน้ำพริกกะปิ หรือข้าวคลุกกะปิรสชาติเข้มข้น' },
      hi: { name: 'भुना हुआ झींगा पेस्ट (तेरासी/बेलाचन) 100g', description: 'प्राकृतिक रूप से किण्वित भुना हुआ झींगा पेस्ट, एशियाई सॉस में गहरा उमामी स्वाद जोड़ने के लिए।' },
      zh: { name: '传统烘烤发酵极鲜赤虾酱膏（峇拉煎） 100克', description: '纯天然海捕野生毛虾微咸发酵精制，经慢火预先烘烤脱水，醇香无杂味，只需指甲盖大小即可赋予参巴酱与通菜惊艳的鲜咸冲击。' },
    },
  },
  {
    id: 'bumbu-dapur-komplit',
    category: 'Bumbu Dapur',
    price: 480,
    rating: 4.9,
    reviews: 140,
    stock: 35,
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=1200&q=85',
    accent: '#a16207',
    localizedContent: {
      id: { name: 'Paket Rempah Kering Komplit Nusantara', description: 'Koleksi lengkap rempah kering utuh pilihan: kapulaga, kayu manis, bunga lawang, cengkeh, ketumbar, dan lada putih. Esensial untuk semur dan sup rempah.' },
      en: { name: 'Whole Dry Asian Spices Assortment', description: 'Comprehensive pantry assortment of whole Asian spices: star anise, cinnamon quills, cloves, green cardamom, coriander seeds, and white peppercorn.' },
      ja: { name: '厳選アジアンホールスパイス調味料セット', description: '八角、シナモンスティック、クローブ、カルダモン、コリアンダーシードなど、本格的なスパイス料理に欠かせない乾燥ホールスパイスの詰め合わせ。' },
      tl: { name: 'Kumpletong Whole Dried Spices Pack', description: 'Koleksyon ng buong tuyong pampalasa tulad ng star anise, cinnamon, at cloves para sa pampalasa ng karne at sabaw.' },
      vi: { name: 'Gói Thảo Mộc Nấu Nước Dùng Phở & Tiềm', description: 'Bộ gia vị thảo mộc khô nguyên hạt đầy đủ gồm hoa hồi, quế thanh, thảo quả, đinh hương và hạt mùi, chuyên dùng ninh nước dùng phở bò thơm nức mũi.' },
      th: { name: 'ชุดเครื่องเทศแห้งตุ๋นยาจีนรวมมิตร', description: 'รวมเครื่องเทศแห้งสมุนไพร โป๊ยกั๊ก อบเชย กานพลู และลูกกระวาน สำหรับทำพะโล้หรือตุ๋นซุปกระดูกหมู' },
      hi: { name: 'साबुत सूखे मसालों का विशेष सेट', description: 'स्टार ऐनीज़, दालचीनी, लौंग और इलायची जैसे साबुत मसालों का पूरा सेट, स्वादिष्ट बिरयानी और ग्रेवी के लिए।' },
      zh: { name: '中华南洋精选原粒香辛料大礼包', description: '大红八角、特级桂皮、公丁香、小茴香、白胡椒粒与草果的原粒荟萃包。炖肉卤味、煲牛羊肉靓汤温润回甘。' },
    },
  },

  // --------------------------------------------------------------------------
  // CATEGORY 5: Saus & Kecap (Sauces & Condiments)
  // --------------------------------------------------------------------------
  {
    id: 'kecap-manis-kedelai-hitam',
    category: 'Saus & Kecap',
    price: 320,
    rating: 5.0,
    reviews: 420,
    stock: 80,
    image: 'https://images.unsplash.com/photo-1516714435131-44d6b64dc6a2?auto=format&fit=crop&w=1200&q=85',
    accent: '#262626',
    localizedContent: {
      id: { name: 'Kecap Manis Kedelai Hitam Kental 600ml', description: 'Kecap manis premium dari kedelai hitam pilihan dan gula kelapa alami. Kental, gurih manis legit, memperkaya cita rasa sate, tumisan, dan cocolan sambal.' },
      en: { name: 'Sweet Soy Sauce (Kecap Manis) 600ml', description: 'Thick, molasses-rich Indonesian sweet soy sauce brewed from black soybeans and palm sugar. The foundational condiment for satay, fried noodles, and marinades.' },
      ja: { name: '黒大豆特醸 ケチャップマニス（極甘口醤油） 600ml', description: '厳選された黒大豆とヤシ糖から作られた濃厚でとろみのあるインドネシア甘口醤油。焼き鳥（サテ）、炒め物、煮物の隠し味に絶大な威力を発揮。' },
      tl: { name: 'Kecap Manis (Sweet Soy Sauce) 600ml', description: 'Malapot at matamis na toyo mula sa Indonesia, masarap sawsawan at pampalasa sa inihaw na ulam.' },
      vi: { name: 'Nước Tương Đen Ngọt Đậm Đặc Kecap Manis 600ml', description: 'Nước tương ngọt sánh đen đặc trưng sản xuất từ đậu nành đen và đường thốt nốt nguyên chất, bí quyết vàng cho món xào và sốt ướp nướng.' },
      th: { name: 'ซีอิ๊วหวานสูตรเข้มข้นเกจับมานิส 600ml', description: 'ซีอิ๊วดำหวานเนื้อข้นเหนียว รสหวานละมุนจากน้ำตาลมะพร้าวธรรมชาติ ใช้หมักย่าง ผัด หรือจิ้มก็อร่อยเลิศ' },
      hi: { name: 'मीठा सोया सॉस (केकैप मनिस) 600ml', description: 'गाढ़ा और मीठा इंडोनेशियाई सोया सॉस, नूडल्स, बारबेक्यू और मैरिनेड के लिए बेहतरीन।' },
      zh: { name: '印尼传统纯酿黑豆甜酱油（甜油露） 600毫升', description: '精选高油黑豆与天然棕榈树糖膏经日光天然陈酿，质感黏稠如蜜，咸甜回味悠长。做沙爹蘸酱、烤肉淋汁或快炒南洋面食之灵魂。' },
    },
  },
  {
    id: 'kecap-asin-shoyu-jepang',
    category: 'Saus & Kecap',
    price: 360,
    rating: 4.9,
    reviews: 260,
    stock: 65,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=1200&q=85',
    accent: '#1e293b',
    localizedContent: {
      id: { name: 'Kecap Asin Shoyu Jepang 500ml', description: 'Kecap asin Jepang fermentasi alami dari gandum dan kedelai. Rasa asin gurih seimbang dan wangi fermentasi khas untuk sushi, sashimi, dan tumisan.' },
      en: { name: 'Japanese Naturally Brewed Shoyu Soy Sauce 500ml', description: 'Authentic Japanese dark soy sauce naturally brewed from soybeans and wheat. Perfectly balanced umami aroma for sushi, ramen broths, and dressings.' },
      ja: { name: '本醸造 国産丸大豆特選醤油 500ml', description: '大豆と小麦をじっくり熟成させた本醸造濃口醤油（500ml）。豊かな香りと芳醇な旨味が、お刺身、煮物、炒め物を格上げします。' },
      tl: { name: 'Japanese Shoyu Soy Sauce 500ml', description: 'Purong Japanese toyo na may natural na umami para sa sashimi, sushi, at marami pang ulam.' },
      vi: { name: 'Nước Tương Shoyu Lên Men Tự Nhiên Nhật Bản 500ml', description: 'Nước tương đậu nành truyền thống Nhật Bản lên men tự nhiên, hương thơm tinh tế vị mặn dịu êm, tuyệt vời khi chấm sushi hoặc nấu mì ramen.' },
      th: { name: 'โชยุซีอิ๊วญี่ปุ่นหมักธรรมชาติ 500ml', description: 'ซีอิ๊วญี่ปุ่นหมักจากถั่วเหลืองธรรมชาติ รสชาติอูมามิกลมกล่อม สำหรับจิ้มซูชิ ซาชิมิ หรือปรุงน้ำซุป' },
      hi: { name: 'प्राकृतिक रूप से ब्रू किया हुआ जापानी शोयू सोया सॉस 500ml', description: 'सोयाबीन और गेहूं से प्राकृतिक रूप से तैयार किया गया शुद्ध जापानी सोया सॉस, सुशी और सूप के लिए।' },
      zh: { name: '日式古法本酿造特选浓口酱油 500毫升', description: '严格遵循日本传统发酵酿造工艺，非转基因大豆与小麦低温慢熟，鲜甜适口香气醇厚，生食点蘸寿司生鱼片或佐餐烹饪相得益彰。' },
    },
  },
  {
    id: 'saus-tiram-premium',
    category: 'Saus & Kecap',
    price: 390,
    rating: 4.8,
    reviews: 185,
    stock: 50,
    image: 'https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?auto=format&fit=crop&w=1200&q=85',
    accent: '#475569',
    localizedContent: {
      id: { name: 'Saus Tiram Ekstrak Asli 510g', description: 'Saus tiram kental bermutu tinggi dari ekstrak tiram asli. Memberikan kilau indah dan rasa gurih gurih umami lezat pada masakan tumis kangkung dan daging.' },
      en: { name: 'Premium Oyster Sauce 510g', description: 'Rich, glossy oyster sauce made from real oyster extracts. Imparts deep savory umami and velvety texture to stir-fried greens and meat glazes.' },
      ja: { name: '極上オイスターソース（牡蠣油） 510g', description: '本物の新鮮な牡蠣エキスを贅沢に凝縮した濃厚オイスターソース（510g）。炒め物にツヤと奥深いコクを与え、中華・アジア料理をプロの味に。' },
      tl: { name: 'Premium Oyster Sauce 510g', description: 'Malapot na oyster sauce na gawa sa totoong talaba, pampalasa sa ginisang gulay at mga lutuing karne.' },
      vi: { name: 'Dầu Hào Thượng Hạng Chiết Xuất Hàu Tự Nhiên 510g', description: 'Dầu hào sánh mịn màu nâu cánh gián chiết xuất từ hàu biển thật, gia vị kỳ diệu mang lại độ bóng đẹp và vị ngọt mặn hài hòa cho món xào.' },
      th: { name: 'ซอสหอยนางรมพรีเมียมเข้มข้น 510g', description: 'ซอสหอยนางรมแท้สูตรเข้มข้น รสชาติกลมกล่อมกลิ่นหอมละมุน ช่วยเพิ่มสีสันและความอร่อยให้จานผัดและหมัก' },
      hi: { name: 'प्रीमियम ऑयस्टर सॉस 510g', description: 'असली ऑयस्टर के अर्क से बना गाढ़ा और स्वादिष्ट सॉस, सब्जियों और मीट को चमकदार व स्वादिष्ट बनाने के लिए।' },
      zh: { name: '特选真鲜蚝汁头抽蚝油 510克', description: '采用上等新鲜牡蛎鲜汁慢火熬缩提炼，质地稠滑红亮，鲜度纯粹自然无味精感，快火炒时蔬或肉丝上光提鲜之法宝。' },
    },
  },
  {
    id: 'minyak-wijen-murni',
    category: 'Saus & Kecap',
    price: 490,
    rating: 4.9,
    reviews: 195,
    stock: 40,
    image: 'https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?auto=format&fit=crop&w=1200&q=85',
    accent: '#ca8a04',
    localizedContent: {
      id: { name: 'Minyak Wijen Panggang Murni 100% 250ml', description: 'Minyak wijen murni hasil pemerasan biji wijen panggang berkualitas. Cukup beberapa tetes untuk menghadirkan keharuman nutty yang menggoda selera.' },
      en: { name: 'Pure Toasted Sesame Oil 100% 250ml', description: 'Cold-pressed 100% pure toasted sesame oil. Intensely aromatic with deep nutty notes, perfect as a finishing oil for soups, noodles, and marinades.' },
      ja: { name: '純正焙煎ごま油 100% 250ml', description: '丁寧に焙煎した白ごまを圧搾した純正ごま油（250ml）。豊かな芳香とコクが料理の仕上げにひと振りするだけで食欲をそそります。' },
      tl: { name: 'Pure Toasted Sesame Oil 250ml', description: 'Mabangong pure sesame oil para sa pampalasa sa sabaw, pansit, at marinades.' },
      vi: { name: 'Dầu Mè Thơm Rang Nguyên Chất 100% 250ml', description: 'Dầu mè rang nguyên chất 100% ép truyền thống thơm nồng nàn vị hạt mè nướng, chỉ vài giọt cuối khi nấu canh hoặc ướp thịt là dậy mùi khó cưỡng.' },
      th: { name: 'น้ำมันงาแท้บริสุทธิ์คั่วหอม 100% 250ml', description: 'น้ำมันงาคั่วบริสุทธิ์ 100% กลิ่นหอมเข้มข้น ใช้เหยาะใส่น้ำซุป ข้าวต้ม หรือหมักเนื้อสัตว์กลิ่นหอมฟุ้ง' },
      hi: { name: 'शुद्ध भुना हुआ तिल का तेल 250ml', description: '100% शुद्ध भुने हुए तिल का तेल, नूडल्स और सूप में सुगंधित स्पर्श जोड़ने के लिए आदर्श।' },
      zh: { name: '纯正冷榨重烘焙小磨黑白芝麻油 250毫升', description: '纯物理石磨压榨100%纯芝麻香油，烘焙火候精准，色泽金红透亮，滴滴浓香四溢。为拉面汤底、凉拌小菜与蒸鱼之绝配。' },
    },
  },
  {
    id: 'kecap-ikan-fermentasi',
    category: 'Saus & Kecap',
    price: 340,
    rating: 4.8,
    reviews: 140,
    stock: 45,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=1200&q=85',
    accent: '#b45309',
    localizedContent: {
      id: { name: 'Kecap Ikan Fermentasi Alami 300ml', description: 'Kecap ikan murni hasil fermentasi teri laut dan garam alami. Mengandung umami alami kuat untuk bumbu dasar sup kimchi, pad thai, atau tumisan sayur.' },
      en: { name: 'Naturally Fermented Fish Sauce 300ml', description: 'Pure artisanal fish sauce extracted from fermented sea anchovies and sea salt. Delivers clean, savory saltiness and umami to Thai and Vietnamese dishes.' },
      ja: { name: '天然熟成 魚醤（ナンプラー／ヌクマム） 300ml', description: 'カタクチイワシと天然塩をじっくり発酵熟成させた伝統の魚醤（300ml）。タイ料理のパッタイ、ベトナム料理のフォーに本場の旨味をもたらします。' },
      tl: { name: 'Patis (Fish Sauce) Pure 300ml', description: 'Purong patis mula sa fermented anchovies, pampalasa sa sabaw ng nilaga, tinola, o sawsawan.' },
      vi: { name: 'Nước Mắm Cốt Cá Cơm Truyền Thống 300ml', description: 'Nước mắm cá cơm than nguyên chất ủ chượp truyền thống độ đạm cao, giọt ngọc hổ phách thơm bùi mặn mòi cho mọi bữa cơm gia đình.' },
      th: { name: 'น้ำปลาแท้หมักธรรมชาติสูตรดั้งเดิม 300ml', description: 'น้ำปลาแท้หมักจากปลากะตักธรรมชาติ กลิ่นหอมรสเค็มกลมกล่อม ไม่เค็มจัด สำหรับปรุงอาหารและทำพริกน้ำปลา' },
      hi: { name: 'प्राकृतिक रूप से किण्वित फिश सॉस 300ml', description: 'समुद्री एंकोवीज़ से बना शुद्ध फ़िश सॉस, थाई और वियतनामी व्यंजनों में उमामी स्वाद के लिए।' },
      zh: { name: '古法木桶纯酿鲜鳀鱼原汁鱼露 300毫升', description: '严选优质小海鳀鱼与天然海盐经长年木桶天然日晒发酵，鲜度极高无人工添加。为泰式金边粉、越南生牛肉河粉及家常炒菜之秘制调味。' },
    },
  },
  {
    id: 'santan-kelapa-kental',
    category: 'Saus & Kecap',
    price: 210,
    rating: 4.9,
    reviews: 280,
    stock: 90,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=1200&q=85',
    accent: '#f8fafc',
    localizedContent: {
      id: { name: 'Santan Kelapa Kental Murni 400ml', description: 'Santan kelapa murni siap pakai dari perasan pertama kelapa tua segar. Tekstur kental gurih, tanpa bahan pengawet, cocok untuk opor, rendang, dan kolak.' },
      en: { name: 'Pure Rich Coconut Milk 400ml', description: 'Rich, creamy first-press coconut milk. Free from preservatives, ideal for Southeast Asian curries, laksa soups, rice dishes, and desserts.' },
      ja: { name: '特濃ココナッツミルク缶 400ml', description: '良質なココナッツの果肉から絞った濃厚でクリーミーな1番搾りココナッツミルク（400ml）。タイカレー、デザート、煮込み料理に。' },
      tl: { name: 'Pure Coconut Milk (Gata) 400ml', description: 'Puro at malapot na gata ng niyog para sa masasarap na ginataan, bicol express, at kakanin.' },
      vi: { name: 'Nước Cốt Dừa Tươi Đậm Đặc 400ml', description: 'Nước cốt dừa ép đầu sóng sánh béo ngậy tự nhiên, tuyệt hảo khi nấu cà ri, bánh chè hoặc sốt tráng miệng thơm nức mùi dừa.' },
      th: { name: 'หัวกะทิแท้เข้มข้น 100% 400ml', description: 'หัวกะทิแท้คั้นสดเข้มข้น มันอร่อย สำหรับทำแกงเผ็ด แกงกะทิ หรือทำขนมหวานไทยโบราณ' },
      hi: { name: 'शुद्ध गाढ़ा नारियल का दूध (कोकोनट मिल्क) 400ml', description: 'ताज़ा और मलाईदार नारियल का दूध, करी, सूप और स्वादिष्ट मिठाइयों के लिए बिल्कुल सही।' },
      zh: { name: '南洋纯正冷榨特浓鲜椰浆 400毫升', description: '初榨新鲜老椰肉压榨提炼，色泽如乳、质地浓滑、椰香天然芳馥。专用于制作泰式绿咖喱、新加坡叻沙及各款南洋椰汁甜品。' },
    },
  },
  {
    id: 'sambal-terasi-pedas',
    category: 'Saus & Kecap',
    price: 290,
    rating: 4.8,
    reviews: 195,
    stock: 55,
    image: 'https://images.unsplash.com/photo-1588252303782-cb80119abd6d?auto=format&fit=crop&w=1200&q=85',
    accent: '#b91c1c',
    localizedContent: {
      id: { name: 'Sambal Terasi Ulek Pedas Gurih 200g', description: 'Sambal terasi ulek siap santap dengan cabai merah segar, terasi udang bakar, dan tomat. Pedas mantap dan gurih menggugah selera untuk lalapan.' },
      en: { name: 'Spicy Sambal Terasi Chili Relish 200g', description: 'Ready-to-eat Indonesian chili relish pounded with fresh red chilies, roasted shrimp paste, and tomatoes. The ultimate condiment for fried chicken and rice.' },
      ja: { name: '本場インドネシア サンバルトラシ（エビ唐辛子味噌） 200g', description: '赤唐辛子と香ばしい発酵エビペーストをすり潰した万能辛味調味料（200g）。揚げ鶏や白ごはんに添えるだけで本場のパンチある辛さに。' },
      tl: { name: 'Spicy Sambal Terasi Chili Sauce 200g', description: 'Maanghang na Indonesian sambal na may alamang, perpektong sawsawan sa pritong isda at ulam.' },
      vi: { name: 'Tương Ớt Tôm Cay Nồng Sambal Terasi 200g', description: 'Sốt ớt mắm tôm kiểu Indonesia giã tay truyền thống, cay nồng đậm đà khó cưỡng, chấm cùng thịt chiên hoặc ăn kèm cơm trắng.' },
      th: { name: 'น้ำพริกซัมบัลทราซีอินโดนีเซีย 200g', description: 'น้ำพริกเผาตำมือรสเด็ด ผสมพริกสด กะปิกุ้งเคย และมะเขือเทศ ทานคู่กับไก่ทอดและผักสด' },
      hi: { name: 'तीखी साम्बल तेरासी चिली चटनी 200g', description: 'ताज़ी मिर्च और झींगा पेस्ट से बनी तीखी एशियाई चटनी, चावल और तले हुए व्यंजनों के लिए।' },
      zh: { name: '印尼特制香辣石臼参巴虾酱（参巴辣椒酱） 200克', description: '采用鲜红辣椒与烘香赤虾酱以传统石臼研磨而成，保留鲜辣果肉质感与浓厚发酵海味，搭配炸鸡烤鱼爽辣开胃。' },
    },
  },

  // --------------------------------------------------------------------------
  // CATEGORY 6: Mie & Pasta (Noodles & Pasta)
  // --------------------------------------------------------------------------
  {
    id: 'indomie-goreng-spesial',
    category: 'Mie & Pasta',
    price: 180,
    rating: 5.0,
    reviews: 580,
    stock: 120,
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=1200&q=85',
    accent: '#dc2626',
    localizedContent: {
      id: { name: 'Indomie Mi Goreng Spesial (Isi 5 Bungkus)', description: 'Mi instan goreng nomor satu dunia dengan tekstur kenyal dan kombinasi bumbu kecap manis, minyak bawang, dan bawang goreng renyah legendaris.' },
      en: { name: 'Indomie Instant Fried Noodles (Pack of 5)', description: 'World-famous Indonesian instant dry noodles. Features springy noodles, seasoned oil, sweet soy sauce, chili powder, and crispy fried shallots.' },
      ja: { name: 'インドミー・ミーゴレン（激旨焼きそば 5食パック）', description: '世界中で愛される大人気インドネシア風インスタント焼きそば（5食入）。特製甘口醤油とフライドオニオンの絶妙な甘辛風味がクセになります。' },
      tl: { name: 'Indomie Mi Goreng Instant Noodles (Pack of 5)', description: 'Paboritong instant dry noodles sa buong mundo. May masarap na timpla ng toyo, pampalasa, at malutong na sibuyas.' },
      vi: { name: 'Mì Trộn Khô Indomie Mi Goreng (Lốc 5 Gói)', description: 'Mì xào khô ăn liền số một thế giới lừng danh, sợi mì dai ngon kết hợp gói dầu gia vị, nước tương ngọt và hành phi giòn rụm khó quên.' },
      th: { name: 'บะหมี่แห้งกึ่งสำเร็จรูปอินโดมี หมี่โกเรง (แพ็ก 5 ซอง)', description: 'บะหมี่แห้งยอดนิยมอันดับ 1 ของโลก เส้นเหนียวนุ่มคลุกเคล้าซอสหวานน้ำมันหอมเจียว รสชาติกลมกล่อมถูกใจ' },
      hi: { name: 'इन्डोमी इंस्टेंट फ्राइड नूडल्स (5 का पैक)', description: 'विश्व प्रसिद्ध स्वादिष्ट इंस्टेंट नूडल्स, मीठी सोया और कुरकुरे भुने प्याज के अनोखे स्वाद के साथ।' },
      zh: { name: '印尼营多特选原味捞面（5连包）', description: '享誉全球的传奇拌面之王。劲道爽滑面条配以秘制红葱油、甜酱油及香脆葱酥碎，一口入魂，南洋速食第一招牌。' },
    },
  },
  {
    id: 'mie-telur-keriting',
    category: 'Mie & Pasta',
    price: 240,
    rating: 4.8,
    reviews: 115,
    stock: 60,
    image: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=1200&q=85',
    accent: '#f59e0b',
    localizedContent: {
      id: { name: 'Mie Telur Keriting Kering 400g', description: 'Mie telur keriting kering terbuat dari tepung terigu dan telur berkualitas. Kenyal tahan rebus, sempurna untuk mie ayam jamur, bakmi goreng, atau lomie.' },
      en: { name: 'Curly Egg Noodles 400g', description: 'Dried Chinese-style curly egg noodles made with high-protein flour and real eggs. Bouncy texture holds sauces well for chow mein or wonton soup.' },
      ja: { name: '中華ちぢれ卵麺（乾燥エッグヌードル） 400g', description: '厳選小麦と卵で練り上げたちぢれ卵麺（400g）。コシが強くスープやタレとよく絡み、ラーメン、焼きそば、ワンタン麺に大活躍。' },
      tl: { name: 'Curly Egg Noodles 400g', description: 'Masarap at makunat na egg noodles para sa mami, pansit canton, o lomi.' },
      vi: { name: 'Mì Trứng Sợi Vắt Xoăn 400g', description: 'Mì trứng khô sợi xoăn dai làm từ trứng tươi và bột mì cao cấp, không bở nát khi nấu, hoàn hảo cho mì xào giòn hoặc mì hoành thánh.' },
      th: { name: 'บะหมี่ไข่เส้นเกลียวพรีเมียม 400g', description: 'บะหมี่ไข่แห้งเส้นเกลียวเหนียวนุ่ม ไม่อืดง่าย เหมาะสำหรับทำบะหมี่หมูแดง บะหมี่ผัด หรือเกี๊ยวน้ำ' },
      hi: { name: 'कर्ली एग नूडल्स 400g', description: 'उच्च प्रोटीन आटे और ताज़े अंडों से बने कर्ली नूडल्स, चाउमीन और सूप के लिए उपयुक्त।' },
      zh: { name: '经典手工特弹全蛋卷卷面 400克', description: '精选高筋小麦粉与新鲜全蛋揉合压制，波浪卷纹抓汁力强，久煮爽滑弹牙不浑汤，适合制作港式云吞面或广式炒面。' },
    },
  },
  {
    id: 'sanuki-udon-segar',
    category: 'Mie & Pasta',
    price: 360,
    rating: 4.9,
    reviews: 168,
    stock: 50,
    image: 'https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=1200&q=85',
    accent: '#64748b',
    localizedContent: {
      id: { name: 'Sanuki Udon Segar Beku (Isi 3 Porsi)', description: 'Udon khas prefektur Kagawa Jepang dengan tekstur kenyal tebal "koshi" yang nikmat. Cocok disajikan dingin dengan kuah tsuyu atau panas dalam kuah dashi.' },
      en: { name: 'Sanuki Udon Fresh Noodles (3 Servings)', description: 'Authentic thick Japanese Sanuki udon noodles. Features firm, chewy "koshi" texture, delicious in warm dashi broth or chilled with dipping sauce.' },
      ja: { name: '本場讃岐冷凍うどん（コシの極み 3食入）', description: '讃岐伝統の手打ち製法を再現した極上の太打ちうどん（3食入）。モチモチとした力強いコシと滑らかな喉ごしをお楽しみください。' },
      tl: { name: 'Fresh Sanuki Udon Noodles (3 Servings)', description: 'Makapal at makunat na Japanese udon noodles, masarap sa mainit na dashi soup o malamig na dipping sauce.' },
      vi: { name: 'Mì Udon Sanuki Nhật Bản Tươi Dẻo (3 Vắt)', description: 'Mì Udon Sanuki truyền thống Nhật Bản sợi dày dẻo dai đàn hồi chuẩn vị, dùng ăn kèm súp dashi nóng hoặc mì lạnh zaru udon.' },
      th: { name: 'เส้นซานุกิอุด้งสดสไตล์ญี่ปุ่น (3 ก้อน)', description: 'เส้นอุด้งซานุกิแท้ เส้นหนานุ่มเหนียวหนึบเคี้ยวเพลิน ทานร้อนกับน้ำซุปดาชิหรือทานเย็นแบบจุ่มซอส' },
      hi: { name: 'सानुकी उडॉन ताज़ा नूडल्स (3 सर्विंग्स)', description: 'पारंपरिक मोटे जापानी उडॉन नूडल्स, गर्म दाशी शोरबा या ठंडी डिपिंग सॉस में बेहद स्वादिष्ट।' },
      zh: { name: '日本香川赞岐急冻熟乌冬面（3食入）', description: '传承日本四国赞岐传统工艺，面条洁白浑圆，劲道韧滑富有咬劲，冷水过凉配日式冷沾汁或热汤炖煮均软糯弹牙。' },
    },
  },
  {
    id: 'bihun-jagung-premium',
    category: 'Mie & Pasta',
    price: 190,
    rating: 4.8,
    reviews: 95,
    stock: 70,
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=1200&q=85',
    accent: '#fde047',
    localizedContent: {
      id: { name: 'Bihun Jagung Pilihan 350g', description: 'Bihun kenyal transparan dari pati jagung alami pilihan. Tidak mudah patah saat ditumis, kenyal lezat untuk bihun goreng kampung atau bihun kuah bakso.' },
      en: { name: 'Premium Corn Vermicelli Noodles 350g', description: 'Translucent, springy vermicelli noodles made from pure corn starch. Retains firmness without breaking during wok stir-frying or boiling.' },
      ja: { name: '極細コーン春雨・ビーフン 350g', description: '上質なコーンスターチから作られた透明感あふれる春雨・ビーフン（350g）。炒めても切れにくく、スープや焼きビーフンに最適。' },
      tl: { name: 'Bihon (Corn Vermicelli) 350g', description: 'Manipis at makunat na bihon para sa paboritong pansit bihon guisado o sabaw.' },
      vi: { name: 'Bún Khô Tinh Bột Bắp Thượng Hạng 350g', description: 'Bún khô sợi trong dẻo dai từ tinh bột bắp, không bị nát gãy khi xào lửa lớn, thích hợp làm bún xào chay hoặc nấu súp.' },
      th: { name: 'วุ้นเส้นแป้งข้าวโพดพรีเมียม 350g', description: 'วุ้นเส้นเส้นใสเหนียวนุ่ม ผัดแล้วไม่เละขาดง่าย สำหรับทำผัดซีอิ๊ว กุ้งอบวุ้นเส้น หรือยำวุ้นเส้น' },
      hi: { name: 'प्रीमियम कॉर्न वर्मीसेली (सेवई) 350g', description: 'पारदर्शी और लचीले कॉर्न नूडल्स, स्टिर-फ्राई या सूप के लिए बेहतरीन।' },
      zh: { name: '特制金黄无明矾玉米粉丝 350克', description: '选用优质玉米淀粉精制，丝丝晶莹剔透，久泡不烂耐翻炒，做南洋炒米粉、蚂蚁上树或海鲜粉丝煲吸汁入味。' },
    },
  },
  {
    id: 'soba-gandum-hitam',
    category: 'Mie & Pasta',
    price: 340,
    rating: 4.8,
    reviews: 130,
    stock: 45,
    image: 'https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=1200&q=85',
    accent: '#78716c',
    localizedContent: {
      id: { name: 'Soba Gandum Hitam Jepang (Buckwheat) 300g', description: 'Mi soba tradisional Jepang dengan kandungan gandum hitam buckwheat asli. Beraroma kacang alami yang harum, menyehatkan, cocok untuk zaru soba dingin.' },
      en: { name: 'Japanese Buckwheat Soba Noodles 300g', description: 'Traditional Japanese soba noodles crafted from aromatic buckwheat flour. Earthy, nutritious, and refreshing served cold with tsuyu or in warm broth.' },
      ja: { name: '信州手打ち風 八割十割ブレンド生そば 300g', description: '蕎麦本来の豊かな風味と喉ごしが際立つ信州風そば（300g）。冷たいざる蕎麦や温かい鴨南蛮そばで本格蕎麦屋の味を。' },
      tl: { name: 'Japanese Buckwheat Soba Noodles 300g', description: 'Tradisyunal na Japanese buckwheat noodles, masustansya at masarap kainin nang malamig.' },
      vi: { name: 'Mì Kiều Mạch Soba Nhật Bản 300g', description: 'Mì Soba truyền thống làm từ bột kiều mạch tự nhiên giàu chất xơ, hương thơm thanh mát tao nhã, thưởng thức lạnh zaru soba rất sảng khoái.' },
      th: { name: 'เส้นโซบะบัควีทญี่ปุ่นแท้ 300g', description: 'เส้นโซบะทำจากแป้งบัควีทกลิ่นหอมธรรมชาติ อุดมด้วยคุณค่าทางอาหาร เหมาะทานแบบเย็นจุ่มซอสสไตล์ญี่ปุ่น' },
      hi: { name: 'जापानी एक प्रकार का अनाज सोबा नूडल्स 300g', description: 'पारंपरिक जापानी सोबा नूडल्स, पौष्टिक और ठंडे डिपिंग सॉस के साथ ताज़गी देने वाले।' },
      zh: { name: '日本信州风味高比例荞麦面 300克', description: '精研天然高山荞麦全谷粉制作，麦香浓郁低脂健康，冷水冲滤搭配青芥末与鲣鱼酱油，爽冽消暑，食之清雅。' },
    },
  },
  {
    id: 'ramen-tokyo-shoyu',
    category: 'Mie & Pasta',
    price: 380,
    rating: 4.9,
    reviews: 155,
    stock: 50,
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=1200&q=85',
    accent: '#d97706',
    localizedContent: {
      id: { name: 'Mie Ramen Segar Tokyo Shoyu (2 Porsi)', description: 'Set mie ramen segar lengkap dengan kaldu kecap shoyu khas Tokyo. Mie kenyal bertekstur kencang dan kuah gurih aromatik kaya umami.' },
      en: { name: 'Tokyo Shoyu Fresh Ramen Kit (2 Servings)', description: 'Authentic fresh Tokyo style ramen kit with rich soy sauce dashi broth concentrate. Firm springy noodles deliver a genuine ramen-ya experience.' },
      ja: { name: '本格東京醤油生ラーメン（特製スープ付 2食入）', description: 'コシのある中太ちぢれ生麺と、鶏ガラと和風だしが香る芳醇醤油スープのセット（2食入）。名店の本格ラーメンをご家庭で手軽に。' },
      tl: { name: 'Tokyo Shoyu Fresh Ramen Kit (2 Servings)', description: 'Sariwang ramen noodles na may kasamang masarap na shoyu soy sauce broth para sa 2 servings.' },
      vi: { name: 'Set Mì Ramen Tươi Nước Dùng Shoyu Tokyo (2 Phần)', description: 'Gói mì ramen tươi chuẩn vị Tokyo kèm gói cốt súp tương shoyu hầm xương thanh ngọt, sợi mì vàng óng dai sần sật chuẩn nhà hàng.' },
      th: { name: 'ชุดราเมนสดโตเกียวโชยุ (2 ที่)', description: 'ชุดเส้นราเมนสดเหนียวนุ่มพร้อมน้ำซุปโชยุเข้มข้นสไตล์โตเกียว เหมือนได้นั่งทานในร้านราเมนแท้' },
      hi: { name: 'टोक्यो शोयु ताज़ा रेमन किट (2 सर्विंग्स)', description: 'सोया सॉस शोरबे के साथ प्रामाणिक ताज़ा टोक्यो शैली का रेमन किट, रेमन प्रेमियों के लिए।' },
      zh: { name: '东京生切酱油拉面礼盒（附浓汤包 2食入）', description: '严选日式中粗微卷生拉面，口感扎实弹牙，搭配老母鸡与鲣鱼慢熬的高纯度秘制特选酱油浓缩汤底，正宗拉面馆绝妙风味。' },
    },
  },

  // --------------------------------------------------------------------------
  // CATEGORY 7: Beras & Serealia (Rice, Grains & Staples)
  // --------------------------------------------------------------------------
  {
    id: 'beras-pandan-wangi-5kg',
    category: 'Beras & Serealia',
    price: 2150,
    rating: 5.0,
    reviews: 340,
    stock: 30,
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=1200&q=85',
    accent: '#15803d',
    localizedContent: {
      id: { name: 'Beras Pandan Wangi Cianjur Premium 5kg', description: 'Beras aromatik pandan wangi asli Cianjur dengan butiran bulat lonjong. Nasi pulen lembut dan harum pandan alami saat dimasak hangat.' },
      en: { name: 'Fragrant Pandan Jasmine Rice 5kg', description: 'Premium aromatic jasmine/pandan rice. Naturally fragrant, soft, and tender texture when steamed, the perfect accompaniment to Asian curries.' },
      ja: { name: '高級アジアン香り米（パンダンライス／ジャスミン米） 5kg', description: '炊き上がると甘く芳しい香りが漂う厳選香り米（5kg）。タイカレー、ナシレマ、海南チキンライスに相性抜群のふっくら食感。' },
      tl: { name: 'Mabangong Pandan Jasmine Rice 5kg', description: 'Mabangong bigas na malambot at masarap kapag isinaing, perpektong pares sa ulam ng pamilya.' },
      vi: { name: 'Gạo Thơm Hương Lài Jasmine Thượng Hạng 5kg', description: 'Gạo thơm thượng hạng hạt dài đều bóng mẩy, khi nấu tỏa hương hoa lài dịu nhẹ, cơm dẻo mềm ngọt thanh tự nhiên.' },
      th: { name: 'ข้าวหอมมะลิไทยแท้พรีเมียม 5kg', description: 'ข้าวหอมมะลิแท้คัดพิเศษ เมล็ดเรียวยาวขาวใส หุงขึ้นหม้อนุ่มหอมกรุ่นชวนรับประทาน' },
      hi: { name: 'सुगंधित जैस्मीन / पांडान चावल 5kg', description: 'प्राकृतिक रूप से सुगंधित और पकाने पर बेहद कोमल रहने वाले प्रीमियम चावल, एशियाई व्यंजनों के लिए।' },
      zh: { name: '皇室御用特级清香茉莉香米 5公斤', description: '原产地生态种植长粒香米，米粒晶莹透亮无碎米，饭熟满室生香，口感软糯香甜富有弹性，佐餐下饭至臻之选。' },
    },
  },
  {
    id: 'beras-jepang-koshihikari-5kg',
    category: 'Beras & Serealia',
    price: 2450,
    rating: 5.0,
    reviews: 410,
    stock: 25,
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=1200&q=85',
    accent: '#e2e8f0',
    localizedContent: {
      id: { name: 'Beras Jepang Koshihikari Premium 5kg', description: 'Beras Jepang jenis Koshihikari butiran bulat pendek (short-grain). Pulen lengket sempurna untuk sushi, onigiri, atau nasi mangkuk donburi.' },
      en: { name: 'Japanese Koshihikari Rice 5kg', description: 'Premium short-grain Japanese Koshihikari rice. Naturally glossy, sweet, and sticky, ideal for sushi, onigiri rice balls, and everyday meals.' },
      ja: { name: '新潟県産 特A コシヒカリ精米 5kg', description: '日本を代表する最高峰のブランド米・新潟県産コシヒカリ（5kg）。豊かな甘み、もっちりとした粘り、炊きたての輝くツヤをご堪能ください。' },
      tl: { name: 'Japanese Koshihikari Rice 5kg', description: 'De-kalidad na malagkit na bigas mula sa Japan para sa sushi, onigiri, at donburi.' },
      vi: { name: 'Gạo Nhật Bản Koshihikari Cao Cấp 5kg', description: 'Gạo Nhật hạt tròn bóng dẻo đậm đà hương vị truyền thống, lý tưởng để làm cơm cuộn sushi, cơm nắm onigiri và bữa cơm hàng ngày.' },
      th: { name: 'ข้าวญี่ปุ่นโคชิฮิคาริแท้ 5kg', description: 'ข้าวญี่ปุ่นพันธุ์แท้โคชิฮิคาริ เมล็ดสั้นเหนียวนุ่ม มีความเงางามและรสหวานธรรมชาติ สำหรับซูชิและโอนิกิริ' },
      hi: { name: 'जापानी कोशीहिकारी चावल 5kg', description: 'प्रीमियम जापानी छोटे दाने वाले चावल, प्राकृतिक रूप से चिपचिपे और मीठे, सुशी और ओनिगिरी के लिए उत्तम।' },
      zh: { name: '日本特A级越光大米（越光米） 5公斤', description: '日本享负盛名的国宝级短圆粒越光大米。煮熟后颗粒饱满晶莹闪亮，米香清甜软糯且带有恰到好处的黏度，做寿司或直接品尝回甘悠长。' },
    },
  },
  {
    id: 'beras-ketan-putih-1kg',
    category: 'Beras & Serealia',
    price: 380,
    rating: 4.8,
    reviews: 135,
    stock: 50,
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=1200&q=85',
    accent: '#f1f5f9',
    localizedContent: {
      id: { name: 'Beras Ketan Putih Murni 1kg', description: 'Beras ketan putih butir panjang bersih berkualitas tinggi. Sangat pulen dan kenyal, bahan utama lemper, lupis, ketan mangga (mango sticky rice), atau uli.' },
      en: { name: 'White Glutinous Sweet Sticky Rice 1kg', description: 'High-quality sweet glutinous white rice. Perfectly sticky and tender for Thai mango sticky rice, Asian rice cakes, and sweet desserts.' },
      ja: { name: '厳選 国産白もち米 1kg', description: 'ふっくら炊き上がり伸びの良い厳選白もち米（1kg）。お赤飯、お餅、アジアンちまき、マンゴースティッキーライス作りに。' },
      tl: { name: 'Malagkit na Bigas (Glutinous Rice) 1kg', description: 'Puting malagkit na bigas para sa masarap na biko, bibingka, at champorado.' },
      vi: { name: 'Gạo Nếp Cái Hoa Vàng Thơm Dẻo 1kg', description: 'Gạo nếp hạt tròn căng mẩy dẻo quánh thơm lừng, nguyên liệu vàng cho món xôi gà, xôi xoài Thái Lan, chè hoặc gói bánh chưng bánh tét.' },
      th: { name: 'ข้าวเหนียวเขี้ยวงูอย่างดี 1kg', description: 'ข้าวเหนียวพันธุ์ดีเมล็ดเรียวสวย หุงแล้วนุ่มเหนียวหอมมัน สำหรับทำข้าวเหนียวมะม่วงหรือข้าวเหนียวหมูปิ้ง' },
      hi: { name: 'सफेद चिपचिपा चावल (ग्लूटिनस राइस) 1kg', description: 'उच्च गुणवत्ता वाले चिपचिपे सफेद चावल, थाई मैंगो राइस और एशियाई मिठाइयों के लिए उत्तम।' },
      zh: { name: '精选纯白圆粒糯米 1公斤', description: '纯净无杂色圆粒晚糯米，煮蒸后质地晶莹黏糯清甜，为制作芒果糯米饭、广式裹蒸粽、八宝饭或香甜年糕之首选。' },
    },
  },
  {
    id: 'tahu-sutera-organik',
    category: 'Beras & Serealia',
    price: 180,
    rating: 4.9,
    reviews: 210,
    stock: 45,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=1200&q=85',
    accent: '#fafafa',
    localizedContent: {
      id: { name: 'Tahu Sutera Organik Halus (Silken Tofu) 300g', description: 'Tahu sutera Jepang bertekstur sehalus puding dari kedelai organik non-GMO. Nikmat dinikmati dingin dengan shoyu, dalam sup miso, atau mapo tofu.' },
      en: { name: 'Organic Fresh Silken Tofu 300g', description: 'Delicate, velvety smooth organic silken tofu made from non-GMO soybeans. Ideal for miso soups, chilled hiyayakko, mapo tofu, and smoothies.' },
      ja: { name: '国産有機絹ごし豆腐 300g', description: '大豆の甘みが口いっぱいに広がるなめらかな絹ごし豆腐（300g）。冷奴、お味噌汁、麻婆豆腐やサラダで極上の舌触りを。' },
      tl: { name: 'Silken Tofu Organic 300g', description: 'Napakalambot at malasutlang tofu, masarap sa miso soup, taho, o mapo tofu.' },
      vi: { name: 'Đậu Hũ Non Hữu Cơ Mịn Màng 300g', description: 'Đậu hũ non hữu cơ làm từ đậu nành sạch mịn như nhung, mềm tan trong miệng, dùng nấu canh rong biển, lẩu nấm hoặc sốt đậu Tứ Xuyên.' },
      th: { name: 'เต้าหู้คินุออร์แกนิกเนื้อเนียนนุ่ม 300g', description: 'เต้าหู้เนื้อนุ่มละมุนลิ้น ทำจากถั่วเหลืองธรรมชาติ สำหรับใส่ในซุปมิโซะ เต้าหู้ทรงเครื่อง หรือทานเย็นกับซีอิ๊ว' },
      hi: { name: 'ऑर्गेनिक सिल्कन टोफू 300g', description: 'मखमली और कोमल ऑर्गेनिक टोफू, मिसो सूप, सलाद और एशियाई व्यंजनों के लिए आदर्श।' },
      zh: { name: '日式天然内酯嫩豆腐（有机绢豆腐） 300克', description: '优选非转基因大豆微滤点浆制成，质地宛若白玉凝脂，滑嫩多汁豆香浓郁，做日式冷奴皮蛋豆腐或四川麻婆豆腐入口即化。' },
    },
  },

  // --------------------------------------------------------------------------
  // CATEGORY 8: Makanan Ringan (Snacks & Crackers)
  // --------------------------------------------------------------------------
  {
    id: 'biskuit-kelapa-renyah',
    category: 'Makanan Ringan',
    price: 220,
    rating: 4.8,
    reviews: 145,
    stock: 65,
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=1200&q=85',
    accent: '#d97706',
    localizedContent: {
      id: { name: 'Biskuit Kelapa Renyah Gurih 200g', description: 'Biskuit kelapa panggang renyah bertabur gula kristal dengan aroma santan kelapa asli. Teman sempurna untuk secangkir kopi atau teh hangat sore hari.' },
      en: { name: 'Crispy Coconut Butter Biscuits 200g', description: 'Crispy oven-baked coconut biscuits infused with real shredded coconut and toasted aroma. A nostalgic teatime snack loved across Asia.' },
      ja: { name: 'サクサク香ばしい ココナッツビスケット 200g', description: '本物のココナッツの甘い香ばしさとサクサク軽い歯ざわりが自慢の焼き菓子（200g）。紅茶やコーヒーのお供にぴったりの懐かしい味わい。' },
      tl: { name: 'Crispy Coconut Biscuits 200g', description: 'Malutong at masarap na biskwit na may lasa ng gata at niyog, bagay sa kape o meryenda.' },
      vi: { name: 'Bánh Quy Dừa Nướng Giòn Rụm 200g', description: 'Bánh quy dừa nướng vàng ruộm thơm lừng mùi dừa tươi giòn tan trong miệng, món bánh ăn vặt nhâm nhi cùng tách trà nóng thơm ngon.' },
      th: { name: 'บิสกิตมะพร้าวอบกรอบหอมมัน 200g', description: 'บิสกิตมะพร้าวอบกรอบ กลิ่นหอมกะทิและมะพร้าวคั่ว หวานมันกำลังดี ทานคู่กับชาหรือกาแฟ' },
      hi: { name: 'कुरकुरे कोकोनट बिस्कुट 200g', description: 'असली नारियल के स्वाद से भरपूर कुरकुरे बिस्कुट, चाय और कॉफी के समय के लिए बेहतरीन स्नैक।' },
      zh: { name: '南洋古早味香烤金黄椰子脆饼 200克', description: '融入纯正椰肉碎与鲜椰乳烘焙出炉，入口酥脆轻盈，满口浓郁椰香久久不散，陪伴午后热茶与咖啡的怀旧惬意点心。' },
    },
  },
  {
    id: 'biskuit-gandum-madu',
    category: 'Makanan Ringan',
    price: 250,
    rating: 4.9,
    reviews: 160,
    stock: 55,
    image: 'https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?auto=format&fit=crop&w=1200&q=85',
    accent: '#b45309',
    localizedContent: {
      id: { name: 'Biskuit Gandum Madu Utuh Sehat 250g', description: 'Biskuit gandum kaya serat dengan sentuhan manis lembut madu alami. Camilan sehat, bernutrisi, dan mengenyangkan untuk menemani aktivitas harian Anda.' },
      en: { name: 'Honey Whole Wheat Digestive Biscuits 250g', description: 'Wholesome digestive biscuits crafted from coarse whole wheat flour and wild honey. High in fiber, nutritious, and satisfying for mindful snacking.' },
      ja: { name: '全粒粉ハニービスケット（食物繊維たっぷり） 250g', description: '香ばしい全粒粉と天然ハチミツのやさしい甘みが溶け合うヘルシービスケット（250g）。食物繊維豊富で朝食やデスクワークのおやつに。' },
      tl: { name: 'Honey Whole Wheat Biscuits 250g', description: 'Masustansyang biskwit na gawa sa whole wheat at purong pulot, masarap at nakakabusog.' },
      vi: { name: 'Bánh Quy Lúa Mạch Mật Ong Tự Nhiên 250g', description: 'Bánh quy lúa mì nguyên cám giàu chất xơ kết hợp vị ngọt dịu nhẹ của mật ong rừng, bữa phụ lành mạnh bổ dưỡng cho cả gia đình.' },
      th: { name: 'บิสกิตโฮลวีตราดน้ำผึ้งแท้ 250g', description: 'บิสกิตแป้งโฮลวีตผสมน้ำผึ้งธรรมชาติ อุดมด้วยไฟเบอร์และใยอาหาร ขนมขบเคี้ยวเพื่อสุขภาพ' },
      hi: { name: 'हनी होल व्हीट डाइजेस्टिव बिस्कुट 250g', description: 'साबुत गेहूं और शहद से बने पौष्टिक डाइजेस्टिव बिस्कुट, फाइबर से भरपूर और सेहतमंद।' },
      zh: { name: '全麦粗粮天然野生蜂蜜营养消化饼 250克', description: '精磨全粒麦粉融入野生金蜜慢火烘培，富含高膳食纤维，口感麦香浓郁微甜不腻，健康轻食与代餐能量的优选。' },
    },
  },
  {
    id: 'kerupuk-udang-sidoarjo',
    category: 'Makanan Ringan',
    price: 360,
    rating: 4.9,
    reviews: 180,
    stock: 50,
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=1200&q=85',
    accent: '#f97316',
    localizedContent: {
      id: { name: 'Kerupuk Udang Sidoarjo Asli Siap Goreng 250g', description: 'Kerupuk udang mentah khas Sidoarjo dari daging udang segar asli. Mengembang sempurna saat digoreng, super renyah dan gurih mantap.' },
      en: { name: 'Authentic Prawn Crackers (Raw) 250g', description: 'Traditional uncooked prawn crackers made from fresh sea prawns and tapioca. Expands into giant, ultra-crisp, and savory chips when deep-fried.' },
      ja: { name: '本場インドネシア プレミアム生えびせんべい 250g', description: '新鮮な天然海老の身をたっぷり練り込んだ未調理えびせんべい（250g）。油で揚げると何倍にも大きく膨らみ、極上のサクサク感を楽しめます。' },
      tl: { name: 'Prawn Crackers (Kropeck) 250g', description: 'Masarap at malutong na kropeck na may totoong lasa ng hipon, masarap iprito at isawsaw sa suka.' },
      vi: { name: 'Bánh Phồng Tôm Thượng Hạng 250g', description: 'Bánh phồng tôm nguyên chất loại đặc biệt nhiều tôm, chiên ngập dầu nở to phồng xốp giòn rụm thơm lừng mùi tôm tươi.' },
      th: { name: 'ข้าวเกรียบกุ้งแท้พร้อมทอด 250g', description: 'ข้าวเกรียบกุ้งแผ่นดิบทำจากเนื้อกุ้งแท้ ทอดในน้ำมันร้อนๆ ฟูกรอบอร่อย ทานเพลินหยุดไม่อยู่' },
      hi: { name: 'प्रामाणिक प्रॉन्स क्रैकर्स (कच्चा) 250g', description: 'ताज़ी झींगा मछली से बने कुरकुरे प्रॉन्स क्रैकर्स, तलने पर बड़े और बेहद कुरकुरे बन जाते हैं।' },
      zh: { name: '印尼传统纯虾肉高蓬特脆大虾片（生胚） 250克', description: '以高比例新鲜海虾肉与木薯生粉槌打制胚，油炸瞬间膨大数倍，入口如云朵般轻盈酥脆、虾香四溢，东南亚佐餐极品脆片。' },
    },
  },
  {
    id: 'emping-melinjo-super',
    category: 'Makanan Ringan',
    price: 420,
    rating: 4.8,
    reviews: 120,
    stock: 40,
    image: 'https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?auto=format&fit=crop&w=1200&q=85',
    accent: '#facc15',
    localizedContent: {
      id: { name: 'Emping Melinjo Asli Super Tipis 250g', description: 'Keripik emping melinjo mentah kualitas ekspor, tipis dan renyah. Rasa gurih dengan sentuhan pahit khas yang nikmat untuk teman soto dan gado-gado.' },
      en: { name: 'Melinjo Nut Crackers (Emping) 250g', description: 'Traditional thin melinjo nut crisps. Lightly bitter and delightfully savory when fried, the quintessential accompaniment to Indonesian soto soups.' },
      ja: { name: 'メリンジョの実のチップス（生ウンピン） 250g', description: 'グネツムの木の実（メリンジョ）を薄く叩いて乾燥させた伝統チップス（250g）。独特のほろ苦さと香ばしい旨味が癖になる逸品です。' },
      tl: { name: 'Emping Melinjo Nut Crackers 250g', description: 'Tradisyunal na emping crackers na may kakaibang linamnam at bahagyang pait, masarap iprito.' },
      vi: { name: 'Bánh Phồng Hạt Melinjo Giòn Rụm 250g', description: 'Món bánh giòn truyền thống làm từ hạt melinjo đập mỏng, vị bùi béo pha chút đắng nhẹ độc đáo ăn kèm súp hoặc làm mồi nhắm.' },
      th: { name: 'ข้าวเกรียบเมล็ดเมลินโจ (เอมปิง) 250g', description: 'ข้าวเกรียบเมล็ดเมลินโจทอดกรอบ รสมันปนขมนิดๆ มีเอกลักษณ์ เข้ากันได้ดีกับน้ำซุปและอาหารจานเดียว' },
      hi: { name: 'मेलिंजो नट क्रैकर्स (एम्पिंग) 250g', description: 'पारंपरिक कुरकुरा स्नैक, हल्का कड़वा और बेहद स्वादिष्ट, सूप और करी के साथ परोसने के लिए।' },
      zh: { name: '印尼特级纯手工压制买麻藤坚果薄脆片（恩饼） 250克', description: '甄选野生买麻藤坚果（Melinjo）手工锤打薄片，油炸后微苦回甘、浓香酥脆，印尼搭配索托汤或印尼沙拉不可或缺之特色脆片。' },
    },
  },
  {
    id: 'kacang-kulit-sangrai',
    category: 'Makanan Ringan',
    price: 290,
    rating: 4.8,
    reviews: 95,
    stock: 60,
    image: 'https://images.unsplash.com/photo-1567894340315-735d7c361db0?auto=format&fit=crop&w=1200&q=85',
    accent: '#d97706',
    localizedContent: {
      id: { name: 'Kacang Kulit Sangrai Gurih 400g', description: 'Kacang tanah pilihan berkulit disangrai garing dengan rempah bawang gurih alami. Renyah, gurih, dan bebas minyak.' },
      en: { name: 'Roasted Garlic In-Shell Peanuts 400g', description: 'Crisp oven-roasted in-shell peanuts infused with aromatic garlic and sea salt. Non-greasy and addictive snack.' },
      ja: { name: '香ばし殻付きローストピーナッツ（塩ガーリック味） 400g', description: '厳選落花生を殻ごと香ばしく焙煎。ガーリックと自然塩の豊かな風味が広がるノンフライ健康おつまみです。' },
      tl: { name: 'Roasted In-Shell Peanuts 400g', description: 'Mano-manong inihaw na mani na may balat at lasang bawang, napakasarap kutkutin.' },
      vi: { name: 'Đậu Phộng Rang Muối Tỏi Nguyên Vỏ 400g', description: 'Đậu phộng rang cát nguyên vỏ thơm nức vị tỏi ớt, hạt mẩy giòn tan, không dầu mỡ.' },
      th: { name: 'ถั่วลิสงอบกระเทียมทั้งเปลือก 400g', description: 'ถั่วลิสงคัดพิเศษคั่วทั้งเปลือกหอมกลิ่นกระเทียม เคี้ยวเพลิน กรอบมันไร้น้ำมัน' },
      hi: { name: 'भुनी हुई लहसुन मूंगफली (छिलके सहित) 400g', description: 'लहसुन और सेंधा नमक के स्वाद से भरपूर कुरकुरी भुनी हुई साबुत मूंगफली।' },
      zh: { name: '古法柴火香烤蒜香带壳花生 400克', description: '严选当季饱满大花生，带壳砂锅慢火煨烤，蒜香入味颗粒酥脆，无油健康佐茶下酒小吃。' },
    },
  },
  {
    id: 'keripik-singkong-balado',
    category: 'Makanan Ringan',
    price: 260,
    rating: 4.9,
    reviews: 230,
    stock: 70,
    image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=1200&q=85',
    accent: '#dc2626',
    localizedContent: {
      id: { name: 'Keripik Singkong Pedas Manis Balado 200g', description: 'Keripik singkong renyah dengan balutan bumbu balado cabai asli pedas manis gurih yang bikin ketagihan.' },
      en: { name: 'Spicy Sweet Balado Cassava Chips 200g', description: 'Thin, extra-crunchy cassava crisps glazed with authentic spicy and sweet caramelized red chili balado sambal.' },
      ja: { name: 'ピリ辛バラド キャッサバチップス 200g', description: '極薄カットのキャッサバ芋をサクサクに揚げ、本場インドネシアの甘辛チリ（バラド）を絡めたやみつきスナック。' },
      tl: { name: 'Spicy Sweet Balado Cassava Chips 200g', description: 'Manipis at malutong na cassava chips na may matamis at maanghang na balado glaze.' },
      vi: { name: 'Snack Khoai Mì Sốt Ớt Cay Ngọt Balado 200g', description: 'Khoai mì thái lát mỏng sấy giòn áo lớp sốt ớt đỏ rim đường cay cay ngọt ngọt thơm bùi đậm vị.' },
      th: { name: 'มันสำปะหลังทอดกรอบซอสบาลาโดเผ็ดหวาน 200g', description: 'มันสำปะหลังแผ่นบางกรอบเคลือบซอสพริกบาลาโดรสเผ็ดหวานกลมกล่อม เคี้ยวเพลิน' },
      hi: { name: 'तीखे-मीठे कसावा चिप्स (बालाडो) 200g', description: 'पतले और कुरकुरे कसावा चिप्स जिन पर तीखी और मीठी मिर्च का ग्लेज चढ़ा है।' },
      zh: { name: '南洋风味甜辣巴拉多木薯脆片 200克', description: '原切特级木薯薄片金黄酥脆，均匀裹满印尼传统秘制红鲜辣椒与焦糖巴拉多酱，甜辣爽脆回味无穹。' },
    },
  },
  {
    id: 'permen-jahe-klasik',
    category: 'Makanan Ringan',
    price: 180,
    rating: 4.8,
    reviews: 88,
    stock: 80,
    image: 'https://images.unsplash.com/photo-1582058091505-f87a2e55a40f?auto=format&fit=crop&w=1200&q=85',
    accent: '#78350f',
    localizedContent: {
      id: { name: 'Permen Jahe Tradisional Hangat 150g', description: 'Permen jahe kenyal kuno dari ekstrak jahe murni dan gula tebu. Menghangatkan tenggorokan dan badan seketika.' },
      en: { name: 'Traditional Chewy Ginger Candies 150g', description: 'Chewy artisan ginger sweets crafted with real Indonesian ginger extract and unrefined cane sugar. Soothing for throat and warming.' },
      ja: { name: '本格生姜のど飴・ソフト生姜キャンディ 150g', description: '天然生姜エキスと粗糖で仕込んだソフトタイプの生姜飴（150g）。ピリッとした生姜本来の辛味と優しい甘さで喉を潤します。' },
      tl: { name: 'Chewy Ginger Candy 150g', description: 'Tradisiyunal na kendi na gawa sa purong luya, pampainit ng lalamunan at katawan.' },
      vi: { name: 'Kẹo Gừng Dẻo Truyền Thống Ấm Bụng 150g', description: 'Kẹo dẻo gừng làm từ nước cốt gừng tươi và mật mía dẻo thơm, vị cay nồng tự nhiên giúp ấm họng giải cảm tức thì.' },
      th: { name: 'ลูกอมขิงเคี้ยวหนึบสูตรโบราณ 150g', description: 'ลูกอมเนื้อนุ่มหนึบทำจากขิงสดสกัดแท้ ให้ความเผ็ดอุ่นชุ่มคอ บรรเทาอาการระคายเคือง' },
      hi: { name: 'पारंपरिक अदरक चबाने वाली कैंडी 150g', description: 'असली अदरक के अर्क से बनी चबाने वाली कैंडी, गले को आराम और शरीर को गर्माहट देती है।' },
      zh: { name: '纯古法老姜汁软糖 150克', description: '高山小黄姜纯榨鲜汁搭配未精炼甘蔗糖慢熬精制，姜辣浓郁微甜软糯，驱寒暖胃润喉生津。' },
    },
  },
  {
    id: 'wafer-roll-cokelat',
    category: 'Makanan Ringan',
    price: 240,
    rating: 4.9,
    reviews: 175,
    stock: 65,
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=1200&q=85',
    accent: '#451a03',
    localizedContent: {
      id: { name: 'Wafer Roll Cokelat Lumer 200g', description: 'Wafer gulung renyah dengan isian krim cokelat pekat lumer berlimpah. Camilan favorit keluarga segala usia.' },
      en: { name: 'Crispy Chocolate Crepe Wafer Rolls 200g', description: 'Crispy wafer rolls filled with rich, molten cocoa cream filling. An irresistible indulgence for coffee breaks.' },
      ja: { name: 'とろけるショコラロールウェハース 200g', description: 'サクサク香ばしいロール状ウェハースの中に濃厚なめらかチョコレートクリームがたっぷり。大人から子どもまで大人気。' },
      tl: { name: 'Chocolate Wafer Sticks 200g', description: 'Malutong na wafer roll na puno ng masarap na tsokolate sa loob.' },
      vi: { name: 'Bánh Quế Cuộn Kem Socola Đậm Đà 200g', description: 'Bánh que kem ống giòn rụm bên ngoài, ngập tràn kem socola béo ngậy tan chảy ngọt ngào bên trong.' },
      th: { name: 'เวเฟอร์โรลสอดไส้ช็อกโกแลตเข้มข้น 200g', description: 'เวเฟอร์อบกรอบม้วนสอดไส้ครีมช็อกโกแลตแท้เต็มแท่ง หวานหอมกลมกล่อม' },
      hi: { name: 'कुरकुरे चॉकलेट वेफर रोल्स 200g', description: 'कुरकुरे वेफर रोल्स जिनमें अंदर गाढ़ी और स्वादिष्ट चॉकलेट क्रीम भरी होती है।' },
      zh: { name: '酥香黑可可熔岩注心蛋卷 200克', description: '多层薄脆蛋卷裹入浓郁幼滑黑巧夹心，入口酥脆轻盈，醇厚可可香瞬间迸发，午后甜点首选。' },
    },
  },
  {
    id: 'teh-melati-celup',
    category: 'Makanan Ringan',
    price: 220,
    rating: 4.9,
    reviews: 190,
    stock: 75,
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=1200&q=85',
    accent: '#047857',
    localizedContent: {
      id: { name: 'Teh Celup Melati Asli Wangi Alami (25 Kantong)', description: 'Teh hitam aromatik berpadu kuntum bunga melati segar asli. Harum semerbak dan menenangkan tubuh.' },
      en: { name: 'Authentic Jasmine Tea Bags (25 count)', description: 'Premium fragrant black tea blended with fresh jasmine blossoms. Floral aroma and soothing taste for all-day sipping.' },
      ja: { name: '本格アジアン ジャスミンティー（25包）', description: '摘みたての天然ジャスミンの花で香りづけした香り高いアジアンティー（25パック）。上品な香りと爽やかな後味。' },
      tl: { name: 'Mabangong Jasmine Tea Bags (25 pcs)', description: 'Mabangong tsaa na may likas na amoy ng jasmine blossoms, nakakarelax inumin.' },
      vi: { name: 'Trà Lài Túi Lọc Thơm Ngát Tự Nhiên (25 gói)', description: 'Trà búp ướp hoa nhài tươi tự nhiên hương thơm thanh tao thuần khiết, thư giãn tinh thần và thanh nhiệt cơ thể.' },
      th: { name: 'ชาดอกมะลิแท้ชนิดซองชง (25 ซอง)', description: 'ชาคัดพิเศษอบด้วยดอกมะลิสดแท้ หอมละมุน สดชื่น ผ่อนคลายทุกครั้งที่ดื่ม' },
      hi: { name: 'प्रामाणिक जैस्मीन टी बैग्स (25 टी बैग्स)', description: 'ताज़े चमेली के फूलों से सुगंधित प्रीमियम चाय, सुगंधित और शरीर को ताज़गी देने वाली।' },
      zh: { name: '天然窨制清香茉莉花茶包（25袋入）', description: '精选高山绿茶嫩芽经伏天茉莉鲜花多道古法窨制，茶汤黄绿澄澈，花香鲜灵持久，入口回甘悠长。' },
    },
  },
];

console.log(`Generated full catalog with ${fullCatalog.length} products!`);
